### ISSUE TITLE
Fuse monads in IR building

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#123]
IRBuilder is monadic and calls into the SchemaTyper monad -- these calls could be fused.

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/ir/impl/IRBuilderContext.scala#L48

**Comment by pstutz** [comment]
Closing, we should probably more fundamentally re-evaluate IRBuilder and typing.
