### ISSUE TITLE
Come up with a caching strategy for eagerly initialised graphs

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#124]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/ir/impl/IRBuilderContext.scala#L73

**Comment by boggle** [comment]
=> Planning of caching intermediary results

**Comment by Mats-SX** [comment]
Obsolete.
