### ISSUE TITLE
Find a good place for Schema -> RecordHeader conversion

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#128]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/api/record/RecordHeader.scala#L172

**Comment by pstutz** [comment]
Part of https://github.com/opencypher/cypher-for-apache-spark/issues/264
