### ISSUE TITLE
Reduce table width when passing through filters

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#130]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/flat/FlatOperatorProducer.scala#L71

Could be related to #121

**Comment by pstutz** [comment]
Connected: Add more precise type information based on predicates

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/logical/LogicalOperator.scala#L116

**Comment by Mats-SX** [comment]
Obsolete since we removed the flat planner.
