### ISSUE TITLE
Schema redesign

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#137]
Consider duplication vs. implied labels

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/test/fixture/OpenCypherDataFixture.scala#L115

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/test/fixture/OpenCypherDataFixture.scala#L110

**Comment by pstutz** [comment]
From TODO in Schema:
```
    // We envision this to change in two ways
    // (1) Only enforce correct types for a property key between implied labels
    // (2) Use union types (and generally support them) for combined labels
    //
```

**Comment by pstutz** [comment]
Ensure implied labels are considered here: https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/api/schema/Schema.scala#L201

**Comment by boggle** [comment]
Move to trello

**Comment by pstutz** [comment]
Fixed by https://github.com/opencypher/cypher-for-apache-spark/pull/218
