### ISSUE TITLE
Consider best semantics for `GraphSource.schema` vs. `GraphSource.graph.schema`

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#139]
Consider caching a computed schema, but maybe defer to implementer?

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/io/file/FileCsvGraphSource.scala#L39

**Comment by boggle** [comment]
I wrote this TODO to suggest caching the schema so we don't load it twice.

**Comment by pstutz** [comment]
`AbstractDataSource` does the schema caching, so this is probably no longer relevant.
