### ISSUE TITLE
Support union types

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#140]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/CAPSRecordsAcceptanceTest.scala#L61

**Comment by pstutz** [comment]
Also change test here: https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/typer/SchemaTyperTest.scala#L319

**Comment by boggle** [comment]
Move to trello

**Comment by Mats-SX** [comment]
While union types are interesting and we might want to move over to that kind of type system, this particular issue has no real value anymore.
