### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#141]
// TODO: Figure out what invariant this was meant to measure

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/CAPSRecordsAcceptanceTest.scala#L127

**Comment by Mats-SX** [comment]
Obsoleted by #679
