### ISSUE TITLE
Refactor test helper class

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#142]
// TODO: Pull out/move over to GraphMatching

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/CAPSRecordsAcceptanceTest.scala#L141

**Comment by Mats-SX** [comment]
Obsoleted by #679
