### ISSUE TITLE
Support unlabeled nodes in GDL

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#143]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/cypher/FunctionsAcceptanceTest.scala#L98

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/cypher/FunctionsAcceptanceTest.scala#L149

**Comment by Mats-SX** [comment]
GDL is located at: https://github.com/s1ck/gdl

**Comment by pstutz** [comment]
Added issue on GDL: https://github.com/s1ck/gdl/issues/36
