### ISSUE TITLE
Fix type inference "Don't know how to type MapExpression"

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#144]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/impl/spark/cypher/FunctionsAcceptanceTest.scala#L186

**Comment by Mats-SX** [comment]
This is a Cypher 9 feature: support for maps. I don't think we need this issue to keep track of it.
