### ISSUE TITLE
Result producer should not discard prev records in scans

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#146]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/physical/PhysicalResultProducer.scala#L64

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/physical/PhysicalResultProducer.scala#L74

**Comment by Mats-SX** [comment]
Obsoleted by #192
