### ISSUE TITLE
Cartesian product should deal with RHS graphs

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#150]
Assert that they are the same?

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/physical/PhysicalResultProducer.scala#L295

**Comment by boggle** [comment]
This should just use the same RHS everywhere. Additionally, let's look into planning caching of intermediary results instead.
