### ISSUE TITLE
Query builder tests should also make assertions about graphs

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#154]
// TODO: Properly assert on graphs, also below

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/ir/impl/CypherQueryBuilderTest.scala#L48

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/ir/impl/CypherQueryBuilderTest.scala#L84

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/ir/impl/CypherQueryBuilderTest.scala#L198

**Comment by Mats-SX** [comment]
Obsolete.
