### ISSUE TITLE
Fix type to value for relationships

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#156]
//TODO: This supports var-expand where we only track rel ids, but it's not right

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/RowUtils.scala#L53

**Comment by DarthMax** [comment]
We now have support for returning a list of relationships in var length expand
