### ISSUE TITLE
Make naming in LogicalOperatorProducer more consistent with other producers

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#163]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/logical/LogicalOperatorProducer.scala#L26

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/logical/LogicalOperatorProducer.scala#L27

**Comment by soerenreichardt** [comment]
Outdated
