### ISSUE TITLE
Generate names for GRAPH OF pattern parts in frontend

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#169]
Might be solved by updating the frontend

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/api/spark/CAPSPatternGraphTest.scala#L64

**Comment by boggle** [comment]
Strange, code for this exists in the frontend AFAIR

**Comment by pstutz** [comment]
I think this might be a feel-good one, where one simply updates the dependency, runs a test, and then starts the day with a fixed TODO. :)
