### ISSUE TITLE
Remove unused BigDecimal conversions

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#174]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/api/value/CypherValue.scala#L394

**Comment by boggle** [comment]
We should have a talk before picking this up. Not convinced we should do this.

**Comment by pstutz** [comment]
The conversion code is already in, just unused. If we're not going to do it, then this issue can be changed to instead remove the currently disabled checks and conversions.

**Comment by Mats-SX** [comment]
Obsoleted -- code already removed.
