### ISSUE TITLE
Make expand ternary (instead of binary)

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#177]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/spark/physical/PhysicalPlanner.scala#L108

**Comment by Mats-SX** [comment]
#192 makes this ternary on the physical layer.

**Comment by pstutz** [comment]
It is indeed ternary now, closing.
