### ISSUE TITLE
Put schema information on CypherType

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#178]
// TODO: Remove EveryEntity here

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/ir/api/pattern/Pattern.scala#L31

**Comment by boggle** [comment]
Can we please move these more high-level issues rather to trello for the time being? Going to put a label on those.
