### ISSUE TITLE
Use lazy CAPSGraph in test

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#182]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/test/support/GraphMatchingTestSupport.scala#L92

**Comment by s1ck** [comment]
Is this still valid? The graph instance is already a `lazy val`.

**Comment by Mats-SX** [comment]
I think the code comment refers to the class `LazyGraph` which lazily loads the graph while providing the schema directly.
