### ISSUE TITLE
Prevent projection of expressions with unfulfilled dependencies

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#183]
Might be connected with #133?

https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/impl/record/InternalHeader.scala#L33

**Comment by boggle** [comment]
There's already code for finding the dependencies, this is a matter of catching any attempt to project what can't be projected.
