### ISSUE TITLE
Move all header creation to FlatPlanner

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#194]
Currently most of the header creation is done in the dedicated planner (FlatPlanner), but not all. Some header calculations are done in the physical layer, which is a layer violation.

A notable example are the `.nodes()` and `.relationships()` calls on the graph interface, which do not take a header, but generate one (from the schema of the graph). These are of course called by the physical scan operations.

**Comment by pstutz** [comment]
We have now removed the header computation from the flat planner instead, so this is no longer relevant.
