### ISSUE TITLE
Initialise empty CAPSRecords without a row

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#197]
Currently `CAPSRecords.unit()` initialises a `DataFrame` with a single empty row. Ideally there should be no rows in an empty `DataFrame`.

**Comment by Mats-SX** [comment]
There's a reason it's called `unit` and not `empty`: the `unit` is what we send as 'driving table' to a query that does not have an explicit driving table specified as input.

**Comment by pstutz** [comment]
Thanks for the explanation.
