### ISSUE TITLE
How to contribute to wiki?

### ISSUE THREAD

**Issue by aolsux** [opencypher/cypher-for-apache-spark#201]
I just tried forking the wiki to add a page and do a PR. Somehow I cant find how to do that. I wrote a small introduction how to use CAPS from within a maven project with IntelliJ. Ill just attach the md file here, maybe you can add it!

HtH Martin
[CAPS-from-maven-project.txt](https://github.com/opencypher/cypher-for-apache-spark/files/1450760/CAPS-from-maven-project.txt)

**Comment by Mats-SX** [comment]
As far as I'm aware, GitHub does not support PRs to the wiki, and not even branches. One can do direct pushes or use GitHub directly for editing.

We haven't yet sorted out our CLA (Contributor's License Agreement) so we can not yet accept contributions, unfortunately. But you are free to spell out the instructions in this issue for example, enabling people to read it. We'll be adding documentation covering the topics covered in your text when we've shipped our first public release.
