### ISSUE TITLE
Evaluate reintroducing second parameter list for Cypher type on `Expr`/`IRField`

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#216]
The problem: We'd like to store the Cypher type for fields and expressions. It is not guaranteed that the types always match when retrieving something, for example from a record header. For this reason they should be considered equal even if the type does not match.

 **Would it really still be a problem if two expressions or fields with different types were not considered equal?** If yes, might it be worth to address these problems in another way?

More specifically: **Might it make sense to only use the relaxed equality where it is specifically required, for example in `RecordHeader` lookups?**

Assuming that we really have to exclude the Cypher type from the default `equals` comparison I see these approaches:
1. Previous approach: **Store the Cypher type in a second parameter list.** This makes it harder to automatically generate instance constructor code and requires ugly dangling parentheses in places where a field/expression is instantiated with the default type. It also has the disadvantage that one cannot pattern match on the Cypher type and the advantage that no blank is needed in pattern matches where the Cypher type is not extracted.
- Option: **Make the Cypher type in the second parameter list an implicit parameter.** This would allow to drop the extra parentheses, but feels like a misuse of implicit parameters.
- Option: **Add a constructor that does not need the Cypher type for all expressions and fields.** This would allow to drop the extra parentheses, but would require writing and maintaining a lot of boilerplate code.
2. Controversial approach from PR: **Use the `ModifiedProduct` trait to exclude the Cypher type from `equals`/`hashCode`**. This reads nicely with the Cypher type as a default parameter. It has the benefit that the Cypher type can be pattern matched, but the drawback that this is mostly not needed and requires an extra blank. The main advantage is that it allows to easily generate instance constructor code, but it breaks the convention that all case class parameters from the first parameter list are included in an equals comparison. It also requires for us to maintain a class that implements our own `equals`/`hashCode` for modified products.

Personally I'd really like it if we could make it so the Cypher type has to match for two expressions or fields to be considered equal. This would require the least amount of extra complexity, because it is perfectly aligned with default case class semantics when the Cypher type is part of the first parameter list.

If this cannot be done and we decide to go back to approach 1 or one of its options, then I'll happily do that refactoring.

**Comment by Mats-SX** [comment]
The disadvantage of having to add extra `()` would rarely appear in production code. I'm not sure how common it will be for users to instantiate these expressions manually, but I expect it to be fairly rare; it's mostly a planner concern. Users will typically write Cypher. In the planner(s), we have an explicit system that tracks and sets the types. So the extra `()` would in the vast majority of cases be our own test code, which does not have elegance as a priority in my opinion.

Not being able to pattern match for the type is an inconvenience, I agree, but it is mild. It will always be possible to do 

```
case a@Expr(...) => a.cypherType
```

I think an unmentioned advantage to using the extra parameter list is that the semantics are well-known for Scala developers. It clearly signals that the type is an extra piece of information (metadata, if you will) and not directly relevant for the class internals.

For pure Scala cleanliness I agree that using only one parameter list would be simpler. However, that argument is borderline saying that extra parameter lists are bad style in general, which I'm not sure I agree with. I think they do make sense sometimes, and that this could be a good case for them.

The thing with the types not being part of equality stems from Cypher itself. Consider this query:

```
MATCH (n)
WITH n, n.foo AS f
WITH n, f, n.bar AS b
WHERE n:Person
RETURN n, f, b, n.foo
```

The type of the variable `n` changes in this query, but the variable is still the same all across. If we made it part of equality this would result in two distinct variables `n`. That could still be workable, but I'm not certain of the consequences. One example might be that we would lose the ability to see `n.foo` in the first `WITH` and `n.foo` in the `RETURN` as the same expression.
