### ISSUE TITLE
create CAPSGraph from data frame

### ISSUE THREAD

**Issue by geoHeil** [opencypher/cypher-for-apache-spark#228]
How can I create a `CAPSGraph` form a spark data frame directly?

**Comment by DarthMax** [comment]
Hej, you can do this using the NodeScan and EdgeScan builders. 
Assuming you have two DataFrames, one for `Person` nodes (schema: `[ID, NAME, AGE, IS_SWEDE]`) and one for `KNOWS` relationships (schema: `[ID, SRC, DST, SINCE]`).

```scala
 val persons = loadPersonDataFrame
 val knows = loadKnowsRelationships

 val `:Person` =
    NodeScan.on("p" -> "ID") {
      _.build
       .withImpliedLabel("Person")
       .withOptionalLabel("Swedish" -> "IS_SWEDE")
       .withPropertyKey("name" -> "NAME")
       .withPropertyKey("age" -> "AGE")
    }
    .from(CAPSRecords.create(persons))

val `:KNOWS` =
    RelationshipScan.on("k" -> "ID") {
      _.from("SRC").to("DST").relType("KNOWS")
       .build
       .withPropertyKey("since" -> "SINCE")
    }
    .from(CAPSRecords.create(knows))

 val graph = CAPSGraph.create(`:Person`, `:KNOWS`)
```

**Comment by s1ck** [comment]
The latest example for graph construction from DataFrames can always be found here: https://github.com/opencypher/cypher-for-apache-spark/blob/master/caps-spark/src/test/scala/org/opencypher/caps/demo/DataFrameExample.scala

**Comment by pstutz** [comment]
Fixed by https://github.com/opencypher/cypher-for-apache-spark/pull/261 and demo example.
