### ISSUE TITLE
Losing entity member slots when entity variable occurs many times

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#240]
The bug is that `Select` drops the label+property slots of `a` because `a` gets several names during semantic analysis. This is related to `ORDER BY` in `RETURN`, which introduces special aliases for variables for some reason, during semantic analysis. I think this is related to the special scoping rules that `ORDER BY` has in `RETURN`.

```
  test("foo") {
    val graph = GDLTestGraph("(:A {v: 1}), (:B {v: 2})")

    val query =
      """MATCH (a)
        |RETURN a
        |  ORDER BY a.v""".stripMargin

    val result = graph.cypher(query)

    result.records.data.show

  }
```

**Comment by DarthMax** [comment]
This works now
