### ISSUE TITLE
issue with documentation code?

### ISSUE THREAD

**Issue by greghines** [opencypher/cypher-for-apache-spark#245]
I just tried to run the code in the readme for this project and get the following error:
scala> import org.opencypher.caps.api.record._
import org.opencypher.caps.api.record._

scala> import org.opencypher.caps.api.spark.{CAPSGraph, CAPSSession}
import org.opencypher.caps.api.spark.{CAPSGraph, CAPSSession}

scala> case class Person(id: Long, name: String) extends Node
<console>:11: error: not found: type Node
       case class Person(id: Long, name: String) extends Node

So the import is happening correctly but something isn't working. Also get the following error:
scala> new Node()
<console>:29: error: trait Node is abstract; cannot be instantiated
       new Node()

Is there a problem with the documentation code or am I missing something?
Cheers

**Comment by pstutz** [comment]
Hi @greghines, thank you for reporting this issue and my apologies for the late reply and the time you spent trying to figure it out.

Unfortunately, you used the readme code just when we split up the repo into modules, and we had forgotten to update the readme. I'll add a [test](https://github.com/opencypher/cypher-for-apache-spark/issues/254) that runs the example so we'll notice when we break the readme code.

It's not fixed just yet, and many changes to the API are underway in a PR. For now, you can find a runnable version of the readme code [here](https://github.com/opencypher/cypher-for-apache-spark/blob/master/caps-spark/src/test/scala/org/opencypher/caps/demo/Example.scala).

I hope that works for you and we'd appreciate any feedback.
