### ISSUE TITLE
Add an example that shows how to use the Neo4j data source

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#305]

**Comment by Mats-SX** [comment]
Setup:

- incoming data from external source (e.g. CSV)
- running database in Neo4j

Workflow:
- connect incoming data to existing Neo4j graph
- issue updates "ad-hoc" through Cypher queries

**Comment by pstutz** [comment]
Fixed by https://github.com/opencypher/cypher-for-apache-spark/pull/313
