### ISSUE TITLE
Nodemapping ignores optional labels

### ISSUE THREAD

**Issue by soerenreichardt** [opencypher/cypher-for-apache-spark#325]
In the nodemapping class cypherType is only defined by implied labels instead of impliedlabels + optional labels. This causes that optional labels cannot be used in scans for example.

**Comment by Mats-SX** [comment]
Interesting observation. I guess there might be a mismatch between our `ScanGraph` model and these optional labels. In the `ScanGraph` model, each `Scan` keeps a set of implied labels and no labels in the data, effectively removing the need for tracking of additional labels. `NodeMapping` supports a slightly wider use case (for custom imports) but there might be inconsistencies between these two models.

**Comment by Mats-SX** [comment]
I believe this is now covered by `NodeMapping` which allows passing in `optionalLabels`, which are read from columns in the table.
