### ISSUE TITLE
Add checks that `CAPSSession` is not null

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#358]
If the implicit is declared after instantiating something such as the Neo4jGraphSource, then the passed implicit session is not initialized and results in a null pointer exception. We should add explicit checks for that and throw a more helpful error.

**Comment by Mats-SX** [comment]
Seems unlikely that this would happen. There are many places where we pass in a `CAPSSession`; checking for `null` at every point seems tedious. If this comes up a lot in certain concrete scenarios we can do something about it -- closing for now.
