### ISSUE TITLE
Upload trimmed-down shaded JARs per each release

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#363]
Build a shaded JAR without Spark and its dependencies, and upload for each tagged release to the releases part of the repository.

We can skip doing this retrospectively for betas 1 and 2 and start with doing it for beta3 onwards.

**Comment by pstutz** [comment]
We prepared this with https://github.com/opencypher/cypher-for-apache-spark/pull/365, need to upload the artefacts with the next beta release.
