### ISSUE TITLE
Feedback 4/5: Document supported parts of Cypher

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#377]
- Reference (partially done [here](https://docs.google.com/spreadsheets/d/1c5_LoI96EYICE6l09rxna-eLO7V-GParEdiHLJJ_Oaw))
 - Example queries

**Comment by sgolecha** [comment]
I am looking at the [OpenCypher Reference](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) and wanted to know what features are supported in CAPS right now.  Is there a document that talks about it ?

One particular feature is the support for multiple edge labels in the Match query - Is this supported ?

![image](https://user-images.githubusercontent.com/421182/50188118-52166600-02d5-11e9-8bd7-69ebfd45c8c7.png)

**Comment by Mats-SX** [comment]
Hello @sgolecha and thanks for reaching out to us.

We do not yet have a comprehensive document on exactly what is supported, but once we get to that it will most likely end up in the [Neo4j Morpheus User Guide](https://neo4j.com/docs/morpheus-user-guide/preview/morpheus-cypher/#morpheus-cypher-support). (Neo4j Morpheus is a commercial product built around CAPS.)

For your particular question: yes, we do support disjunctions on relationship types in pattern matches (although I can find no actual tests for this -- will add).

**Comment by Mats-SX** [comment]
The supported level of Cypher 9 is now covered in this part of the Neo4j Morpheus User Guide: https://neo4j.com/docs/morpheus-user-guide/preview/caps/cypher/cypher9-features/

We will keep updating this as we proceed.
