### ISSUE TITLE
Feedback 11: Document constraints when turning a DF into an entity table

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#379]
- Relationships and nodes need IDs, they must be of type `Long`
- If you have multiple node tables as part of same graph, you can’t use overlapping IDs

**Comment by s1ck** [comment]
* columns storing node and relationship identifiers must be named `id`
* columns storing start node identifiers must be named `source`
* columns storing end node identifiers must be named `target`

**Comment by Mats-SX** [comment]
This is now covered by 

https://github.com/opencypher/cypher-for-apache-spark/blob/52f228eb4ee53f0fcdab5eabce075de00e903d0e/okapi-api/src/main/scala/org/opencypher/okapi/api/io/conversion/NodeMapping.scala#L79-L100

and 

https://github.com/opencypher/cypher-for-apache-spark/blob/52f228eb4ee53f0fcdab5eabce075de00e903d0e/okapi-api/src/main/scala/org/opencypher/okapi/api/io/conversion/RelationshipMapping.scala#L146-L158
