### ISSUE TITLE
Feedback 16: Issue with MultipleGraphExample on Windows

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#384]
Problem related to `Paths.get` from an absolute path in `FileCsvDataSource`

**Comment by Mats-SX** [comment]
@soerenreichardt Can you try to run `MultipleGraphExample` to see if this is still an issue?

**Comment by soerenreichardt** [comment]
Works on my machine. Example tests fail though because of differing line breaks.

**Comment by Mats-SX** [comment]
That seems to me a separate issue. Let's close this.
