### ISSUE TITLE
RecordHeader.selfWithChildren not working for ProjectedField

### ISSUE THREAD

**Issue by s1ck** [opencypher/cypher-for-apache-spark#413]
If the given `Var` refers to a `ProjectedField` (e.g. due to a `WITH`), `selfWithChildren` only returns the projected field. 
This for example leads to wrong keys during grouping, e.g. for `MATCH (n) RETURN n, count(*)`

**Comment by s1ck** [comment]
refers to https://github.com/opencypher/cypher-for-apache-spark/issues/383

TCK: Feature: ReturnAcceptance Scenario: Count star should count everything in scope is a good test case.

**Comment by pstutz** [comment]
Obsolete due to new RH
