### ISSUE TITLE
CypherGraph should handle AllGiven and AnyGiven

### ISSUE THREAD

**Issue by s1ck** [opencypher/cypher-for-apache-spark#42]
Currently, `CypherGraph.nodes` and `CypherGraph.relationships` expect `CTNode` and `CTRelationship` arguments which are handles as `AND` (for ndoes) and `OR` (for rels) internally. To be more generic and also support the `OR` case for nodes (and the `AND` case for rels), the methods should expect `Elements[Label]` and `Elements[RelType]` and match internally.

**Comment by pstutz** [comment]
`AllGiven`/`AnyGiven` were removed.
