### ISSUE TITLE
PGDSAcceptance extension

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#421]
- The `stores a graph` test is successful when `hasGraph` returns `true`, but doesn't actually try a Cypher query on the stored graph. I think it should, ensuring that the actual data has been written and can be retrieved.

- We should define in the contract what is to happen when an attempt is made to store a graph under the same name that already exists; this should be an error (no overwrite), but it should be a well-defined error, similar to what we do with `GraphNotFoundException`

**Comment by pstutz** [comment]
Added more tests for special property names and unicode support here: https://github.com/opencypher/cypher-for-apache-spark/pull/433/files#diff-58730d2c1b97e61db53fe9df87cb4bd0R200

**Comment by Mats-SX** [comment]
Agreed.
