### ISSUE TITLE
Remove variable name from node/rel scans on our main PropertyGraph interfaces

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#424]
Requires unnecessary renaming and prevents caching of node/rel scans.

**Comment by Mats-SX** [comment]
Which interfaces do you mean exactly, and how?

Is it the variable that you send into this function that you want to remove?
```
  def nodes(name: String, nodeCypherType: CTNode = CTNode): CypherRecords
```

Or is it this variable that you want removed?
```
final case class NodeScan(node: Var, in: FlatOperator, header: RecordHeader) extends StackingFlatOperator
```

**Comment by pstutz** [comment]
The first, also on the CAPSGraph interface.

For the second one we probably need a new operator without the variable name, with name assignment as a separate operation. If we can do that, then we can cache and reuse the basic scan.

**Comment by pstutz** [comment]
Will be covered by https://github.com/opencypher/cypher-for-apache-spark/pull/548
