### ISSUE TITLE
License checking documentation does not work as described in README

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#465]
The `license-checking` readme says to run this command: `mvn install -Dcluster -Doverwrite -DskipTests`

That didn't work when I executed it.

**Comment by s1ck** [comment]
Could you elaborate? The README doesn't say anything about license checking.

**Comment by Mats-SX** [comment]
I think he means this readme: https://github.com/opencypher/cypher-for-apache-spark/blob/master/licensecheck-config/README.adoc

**Comment by pstutz** [comment]
Seems to work for everyone else, will do a clean checkout next time I get an error.
