### ISSUE TITLE
Change`InMemoryGraph` to extend the `PropertyGraph` or `CAPSPropertyGraph` trait

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#466]

**Comment by s1ck** [comment]
I think it feels to be the good change, but I'm wondering what the technical advantage is. Just asking with prioritization in mind.

**Comment by pstutz** [comment]
It's not very important, but when integrating changes it was confusing that this is a graph, but doesn't implement our core graph interfaces.

**Comment by pstutz** [comment]
We attempted this, but the different requirements for a property graph and a simple parsing tool are very different and hard to reconcile.
