### ISSUE TITLE
Bag implementation is buggy

### ISSUE THREAD

**Issue by DarthMax** [opencypher/cypher-for-apache-spark#500]
```
Bag(
   CypherMap("p1" -> "a", "p2" -> "a"),
   CypherMap("p1" -> "a", "p2" -> "b"),
   CypherMap("p1" -> "b", "p2" -> "a"),
   CypherMap("p1" -> "b", "p2" -> "b")
) should equal(Bag(
   CypherMap("p2" -> "a", "p1" -> "a"),
   CypherMap("p2" -> "b", "p1" -> "a"),
   CypherMap("p2" -> "a", "p1" -> "b"),
   CypherMap("p2" -> "b", "p1" -> "b")
))
```

This is caused by the way equality is implemented for Bags: it uses `toString` of the inner objects (CypherMap in the above example)

**Comment by pstutz** [comment]
That's odd, these maps should fall into the `Objects.equals(x, y)` case. This means that the order inside the list might be different, but only when the shuffled around elements are equal to each other. Maybe that's not good enough for ScalaTest when checking list equality. Will side-step the issue by using a Map[K=Element, V=Count] representation. Unfortunately the diffs for that are probably not as readable.

**Comment by pstutz** [comment]
https://github.com/opencypher/cypher-for-apache-spark/pull/501
