### ISSUE TITLE
Collect API changes

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#529]
Graph sources rework:
- Import
`import org.opencypher.spark.api.io.csv.CsvDataSource`
 =>
`import org.opencypher.spark.api.GraphSources`
- Usage
`session.registerSource(Namespace("myDataSource"), CsvDataSource(rootPath = graphDir))`
=>
`session.registerSource(Namespace("myDataSource"), GraphSources.fs(rootPath = graphDir).csv)`

**Comment by s1ck** [comment]
Could we move those changes into a github wiki and add API changes for each release?

**Comment by DarthMax** [comment]
We could also add it to the release notes

**Comment by s1ck** [comment]
For the release notes, it would nice to add a list of all closed issues

**Comment by s1ck** [comment]
(since the last release obviously)

**Comment by s1ck** [comment]
https://github.com/opencypher/cypher-for-apache-spark/wiki/API-Changes
