### ISSUE TITLE
Create a graph from Rdd or dataframe and then Store it in Neo4j

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#549]
I am a beginner for Neo4j. Recently i was creating graphes by loading the csv and creating in the main time nodes and their relationships.

now my boss ,who wants a scalable solution,give me a Spark project and want me to process or load the java-pair-rdd and create a graph based on it.

so is your project allows creating graphs from rdd or dataframe  and then Store it in Neo4j?

**Comment by pstutz** [comment]
Hi Haddad,

This is example shows you how to create a graph: https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/DataFrameInputExample.scala

Once you have a graph you can store it to Neo4j by using:
```
val neo4jDS = neo4jGraphSource.cypher.neo4j(...neo4jConfig...)
neo4jDS.store(yourGraph)
```

Please let us know if you should run into troubles.
