### ISSUE TITLE
Scala in Maven project

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#561]
I 'am asking how to use this project ?

this is what i 've done : 
* create a **pom.xml**
 in which i set the project dependencies .

* imported the project in eclipse as **a maven project**
* build the project

Now I need to test the project with your *HELLO CAPS* so i tried to add a Scala class but surprise i can't ?!
I s what i am doing write ?

**Comment by pstutz** [comment]
Hi @HADDADENICAR, the example project might be a good starting point, please reopen the issue of this doesn't work for you: https://github.com/opencypher/caps-examples

**Comment by HADDADENICAR** [comment]
I have opened the caps-examples project with eclipse, but i am not able to run the scala class as a scalaproject
