### ISSUE TITLE
How to Run InputDataFrameExample

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#564]
In order to test InputDataFrameExample , i tried  to run this cmd on ***cypher-for-apache-spark*** folder : 

    mvn scala:run -DmainClass=spark-cypher-examples.src.main.scala.org.opencypher.spark.examples.DataFrameInputExample

but i get this exception :

     [INFO] --- scala-maven-plugin:3.2.1:run (default-cli) @ okapi ---

      java.lang.ClassNotFoundException: spark-cypher-  examples.src.main.scala.org.opencypher.spark.examples.DataFrameInputExample
      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      at scala_maven_executions.MainHelper.runMain(MainHelper.java:154)
      at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
      [INFO] ------------------------------------------------------------------------
      [INFO] Reactor Summary:
      [INFO]
      [INFO] Okapi - openCypher query compilation API and pipeline 1.0.0-SNAPSHOT FAILURE [ 11.993 s]

so how to run DataFrameInputExample ?

**Comment by pstutz** [comment]
Try `mvn scala:run -DmainClass=org.opencypher.spark.examples.DataFrameInputExample` inside of the `spark-cypher-examples` folder. I really recommend you give IntelliJ a try, that's a lot more convenient.

**Comment by pstutz** [comment]
You need to run `mvn install` on the main project so the examples module finds the dependencies for the other modules.

**Comment by pstutz** [comment]
Do you have an existing Hadoop installation that might have a version conflict?

[Vijay @ StackOverflow](https://stackoverflow.com/questions/20584157/unsatisfiedlinkerror-nativeiowindows-access0-when-submitting-mapreduce-job-to):
```
This error generally occurs due to the mismatch in your binary files in your %HADOOP_HOME%\bin folder. So, what you need to do is to get hadoop.dll and winutils.exe specifically for your hadoop version.

Get hadoop.dll and winutils.exe for your specific hadoop version and copy them to your %HADOOP_HOME%\bin folder.
```

**Comment by HADDADENICAR** [comment]
what i have is C:/winutils/bin/winutils.exe and i set that in the Path  to be able to use spark.

**Comment by pstutz** [comment]
Is the Hadoop version compatible?

**Comment by pstutz** [comment]
AFAIK Spark `2.2.1` that we use in out tests depends on Hadoop `2.6.5`

**Comment by HADDADENICAR** [comment]
i have put a hadoop.dll  with the same version as winutils.exe in the Hadoop_home path.
now **the previous error disappear** and new errors in **test function** appears: 
1.

      org.opencypher.spark.api.io.csv.HdfsCsvDataSourceAcceptance *** ABORTED ***
       java.lang.NullPointerException:
       at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
      at org.apache.hadoop.util.Shell.runCommand(Shell.java:483)
     at org.apache.hadoop.util.Shell.run(Shell.java:456)
     at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
     at org.apache.hadoop.util.Shell.execCommand(Shell.java:815)
     at org.apache.hadoop.util.Shell.execCommand(Shell.java:798)
 
  2)    
       
        


         2018-07-19 18:56:53,538 WARN  [ScalaTest-main-running-EdgeListDataSourceTest]  streaming.FileStreamSink (Logging.scala:logWarning(66)) - Error while looking for metadata directory.
    - should return the test graph *** FAILED ***
      java.lang.IllegalArgumentException: Pathname /C:/Users/Ahmed/AppData/Local /Temp/caps_edgelist_15320193128256615490085103964651edgelist from hdfs://127.0.0.1:59876/C:/Users/Ahmed/AppData/Local/Temp/caps_edgelist_15320193128256615490085103964651edgelist is not a valid DFS filename.
     at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:197)
     at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
     at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
     at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
     at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81

3)

    org.opencypher.spark.api.io.csv.MultipleFilesPerTableDataSourceAcceptance *** ABORTED ***
      java.lang.NullPointerException:
     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
     at org.apache.hadoop.util.Shell.runCommand(Shell.java:483)
     at org.apache.hadoop.util.Shell.run(Shell.java:456)
     at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
     at org.apache.hadoop.util.Shell.execCommand(Shell.java:815)
    at org.apache.hadoop.util.Shell.execCommand(S

4.

     DefaultFileSystemTest:
      - creates a data source root folder when it does not exist yet *** FAILED ***
      java.lang.IllegalArgumentException: Pathname /C:/Users/Ahmed/AppData/Local  /Temp/junit5746941656606926400/someNewFolder1/someNewFolder2 from C:/Users/Ahmed/AppData/Local/Temp/junit5746941656606926400/someNewFolder1/someNewFolder2 is not a valid DFS filename.
      at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:197)

5.

       LocalCsvDataSourceAcceptance:
       org.opencypher.spark.api.io.csv.LocalCsvDataSourceAcceptance *** ABORTED ***
       java.lang.IllegalArgumentException: Wrong FS: file://C:\Users\Ahmed\AppData\Local   \Temp\junit7578503280587451291, expected: hdfs://127.0.0.1:59876
       at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:647)
6.

       org.opencypher.spark.api.io.csv.MultipleFilesPerTableDataSourceAcceptance *** ABORTED ***
       java.lang.NullPointerException:
      at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
      at org.apache.hadoop.util.Shell.runCommand(Shell.java:483)
      at org.apache.hadoop.util.Shell.run(Shell.java:456)
      at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)



Run completed in 1 hour, 32 minutes, 3 seconds.
Total number of tests run: 805
Suites: completed 71, aborted 3
Tests: succeeded 803, failed 2, canceled 0, ignored 35, pending 0
*** 3 SUITES ABORTED ***
*** 2 TESTS FAILED ***

**Comment by pstutz** [comment]
Can only give a quick reply: it seems that the temporary directory used by JUnit in Windows contains spaces in a folder name, which I think disallowed by HDFS. Can't look into it atm, but I think it would be most promising to look into changing the temporary directory used by JUnit. Alternatively we could look into if there's a way to convert the JUnit directory name with spaces to a valid HDFS directory. Or use a different way to generate a temporary directory.

**Comment by HADDADENICAR** [comment]
That means the project can't be useful on win 10 environment for this month ?

**Comment by HADDADENICAR** [comment]
The Same thing happen with Intellij IDEA on windows 10 ; with intellij IDEA's Terminal

**Comment by HADDADENICAR** [comment]
there is no run as scala application in Intellij IDEA

**Comment by pstutz** [comment]
Do you have the Scala plugin installed?

**Comment by HADDADENICAR** [comment]
finally after the `mvn clean install` success in #566 `mvn scala:run -DmainClass=org.opencypher.spark.examples.DataFrameInputExample` success too : 
    
     [INFO] ------------------------------------------------------------------------
     [INFO] BUILD SUCCESS
     [INFO] ------------------------------------------------------------------------
     [INFO] Total time: 02:42 min
     [INFO] Finished at: 2018-07-25T01:00:01+01:00
     [INFO] Final Memory: 39M/427M
     [INFO] ------------------------------------------------------------------------

i won't close this issue yet because i still have question on how that works with neo4j

**Comment by HADDADENICAR** [comment]
Hi @pstutz ,

in #549 you told me that in order to store the graph created i need to add this lines to the code : 

    val neo4jDS = GraphSources.cypher.neo4j(yourNeo4jConfig)
      neo4jDS.store(Neo4jPropertyGraphDataSource.defaultGraphName, yourGraph)

but i really  didn't understand what you mean by the Neo4j Config is it the **password** ??

**Comment by HADDADENICAR** [comment]
i have asked that question on slack and they answered me for the **Neo4j Configurations**:
        import java.net.URI
        import org.opencypher.spark.api.io.neo4j.Neo4jConfig
        val boltURI: URI = new URI("bolt://192.168.1.100:7687")
        val neo4jConfig: Neo4jConfig = new Neo4jConfig(boltURI, "my_user_name", Some("my_password"), true)

 i have added that to the code, now the problem comes from the code you suggested : 
      Cannot resolve 'GraphSources'
      Cannot resolve 'store'
      Cannot resolve 'Neo4jPropertyGraphDataSource'

is there some missing imports that i need to add ?

**Comment by HADDADENICAR** [comment]
Again thanks to the help i get from [slack](https://neo4j-users.slack.com/) i could resolve my problem of imports and connections to Neo4j with this code : 
     
     import org.opencypher.spark.api.CAPSSession
     import java.net.URI
     import org.opencypher.spark.api.io.neo4j.Neo4jPropertyGraphDataSource
     import org.opencypher.spark.api.io.neo4j.Neo4jConfig
     import org.opencypher.okapi.api.graph.GraphName

     val session: CAPSSession = CAPSSession.local()

      val boltWriteURI: URI = new URI("bolt://localhost:7687")

      val neo4jWriteConfig: Neo4jConfig = new Neo4jConfig(boltWriteURI, "neo4j", Some("my_password"), true)

      val neo4jResult: Neo4jPropertyGraphDataSource = new   Neo4jPropertyGraphDataSource(neo4jWriteConfig)(session)

     val neo4jResultName: GraphName = new GraphName("neo4jgraph");

     neo4jResult.store(neo4jResultName, yourGraph);

Now i can store and visualize the  graph created with from dataframe in Neo4j . 👍
