### ISSUE TITLE
 The Property type 'ANY?' can not be stored in a Spark column.

### ISSUE THREAD

**Issue by swayam18** [opencypher/cypher-for-apache-spark#573]
We are trying to test drive CAPS on our graph. However, on initialization, we get the following error:

`The property type 'ANY?' for property 'images' can not be stored in a Spark column.`

We don't particularly care about that field or node as of now. How can we workaround this issue?

**Comment by pstutz** [comment]
Hi Swayam, are you using the Neo4j data source on CAPS version `0.1.6`?

**Comment by s1ck** [comment]
You can omit such type compatiblity issues during import using a flag on the data source. If there is an incompatible type (e.g. temporal types), those properties are not loaded. Have a look that this test to see how the flag is being set:

https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-testing/src/test/scala/org/opencypher/spark/api/io/neo4j/Neo4jPropertyGraphDataSourceTest.scala#L83-L94

**Comment by s1ck** [comment]
You can also pass the `omitImportFailures` flag at the `GraphSources`:  https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher/src/main/scala/org/opencypher/spark/api/GraphSources.scala#L70

**Comment by swayam18** [comment]
Thanks @s1ck 
@pstutz, I am usin ghte data source on CAPS version 1.0.0-SNAPSHOT

**Comment by pstutz** [comment]
Hi Swayam, I assume you use the Neo4j DS. I recommend you update to CAPS `0.1.6` and use the parameter suggested by @s1ck:
```
GraphSources.neo4j(yourConfig, omitImportFailures = true)
```

**Comment by swayam18** [comment]
@pstutz Thanks, I upgraded to 0.1.6 and added the omitImportFailures flag. However, I am running into the following issue now:

Neo4j schema procedure not activated. Consider activating the procedure `org.opencypher.okapi.procedures.schema`

I understand I need to install this plugin to neo4j. Where can I find the JAR file for the plugin?

**Comment by pstutz** [comment]
You can find it on the GitHub release page for `0.1.6`, it's called `okapi-neo4j-procedures-0.1.6-cluster.jar`

**Comment by pstutz** [comment]
I don't have a link to the installation instructions. @DarthMax: is there a write-up yet on how to install the procedure?

**Comment by swayam18** [comment]
Hi @pstutz thanks for pointing it out.
However, after running the procedure, it seems to be stuck (its been running for 20mins now, no output)

Anything I can do to fix this?

**Comment by pstutz** [comment]
I add some existing instructions to a wiki page: https://github.com/opencypher/cypher-for-apache-spark/wiki/Neo4j-Schema-Procedure

I didn't yet have the time to test the instructions though.

**Comment by pstutz** [comment]
How large is the database? We significantly [improved the performance of the procedure](https://github.com/opencypher/cypher-for-apache-spark/pull/565) last week, but those improvements have not been released yet.

**Comment by DarthMax** [comment]
Depending on the database size the procedure can run for quite long. 
As Philip already pointed out we improved the performance of the procedure considerably. 
If you want to make use of these changes you could try building CAPS yourself. 

Todo this run the following steps:

1. Clone this repository
2. run `mvn clean install -DskipTest -Dcluster`
3. Copy the file okapi-neo4j-procedues-1.0.0-SNAPSHOT-cluster.jar from CHECKOUT_DIR/okapi-neo4j-procedures/target into the plugins directory of your Neo4j installation
4. Either use the file spark-cypher-1.0.0-SNAPSHOT-cluster.jar from   CHECKOUT_DIR/spark-cypher/target or make sure to update the spark-cypher version to 1.0.0-SNAPSHOT in your project
5. run `CALL org.opencypher.okapi.procedures.schema` in Neo4j browser
6. ???
7. Profit!

:)

**Comment by pstutz** [comment]
@swayam18 it should scale linearly with the DB size. With the improved procedure that @DarthMax described I'd expect it to take ~5 minutes on a ~52GB database with a simple relational-like schema. We have so far only tested the procedure on a 20GB DB.

**Comment by swayam18** [comment]
@pstutz Ah, and this schema computation needs to take place every time a `GraphSource` is registered? 
No way to cache the results? I ask because waiting ~1 hour for larger databases to spin up doesn't make a lot of sense to us. Especially given that one of the use-cases of Spark is to do distributed computation on large scale data. What are your thoughts on this?

**Comment by pstutz** [comment]
@swayam18 You're right, at the moment it needs to be recomputed every time the `Neo4jPGDS` is registered, which can take long on a large DB. Thanks for the suggestion to pass in an existing Schema, this would be a useful feature that should be easy to implement. [I created an issue for it](https://github.com/opencypher/cypher-for-apache-spark/issues/574 ).

**Comment by pstutz** [comment]
The schema is easy to serialize & parse to/from JSON, in case you would like to store it. I'll close this issue for now, please feel free to reopen it if you should run into these issues with the next release. The PR that allows to pass in a schema is [here](https://github.com/opencypher/cypher-for-apache-spark/pull/575), in case you would like to experiment with that option.

**Comment by swayam18** [comment]
Thanks @pstutz, appreciate the quick PR.
