### ISSUE TITLE
Investigate explicitly freeing the resources used by property graph data sources

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#577]
Adding something like `PGDS.close` would allow us to reuse Neo4j driver instances. The issue is that closing the driver synchronously is very slow, and when it is closed asynchronously we risk running out of file handles.

**Comment by s1ck** [comment]
Since a driver instance cannot be shared between spark executors, we need to open them on a partition basis. This leads to `#scans * partitions` driver instances. In the server environments, the number of open files is usually set to a sufficiently high number. I could run the `Neo4jViewPGDSAcceptance` with a local value of 65000. Maybe we should keep with the async close and make sure to increase the value on the system that runs CAPS with Neo.

**Comment by Mats-SX** [comment]
It seems to me that if we can configure our way out of this, that's a preferable option to modifying the interface.

**Comment by pstutz** [comment]
The issue is that the `ulimit` file descriptor is an OS configuration that users have to configure themselves. In some environments users also only have limited/indirect control over these parameters, which might make a fix hard to implement for them. If there are easy ways for us to reduce the number of file handles used by CAPS that might avoid frustration for our users.

**Comment by Mats-SX** [comment]
After googling around a bit, it seems that in general, Spark clusters need a pretty large `ulimit` configuration to work well with parallelisation and shuffling. We might be able to assume that the configuration is sufficiently lenient, based on [Spark using a similar assumption](https://stackoverflow.com/a/25707630/4716082) (anyway, CAPS can't run if Spark can't).

If closing synchronously is slow, how would we be able to do better than upping `ulimit` anyway? Closing async using some kind of pool instead?

**Comment by pstutz** [comment]
I think the best solution would be to fix the problem that prevents our driver from closing quickly, which causes for us to run out of resources in the first place. Chances are that we could improve the driver configuration for our use case and maybe ensure that we don't block a driver thread because we don't fully consume a query result.

**Comment by pstutz** [comment]
Consensus: If a PGDS needs to be closed, do it directly on the PGDS, not managed by the session.
