### ISSUE TITLE
How to Load a Csv into a Dataframe

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#579]
is there a way to load a csv into a dataframe with CAPS ? 

in which directory i can find this path `org.opencypher.spark.impl.io.hdfs.CsvGraphLoader`for the documentation?

**Comment by s1ck** [comment]
Have a look at the examples: https://github.com/opencypher/cypher-for-apache-spark/tree/master/spark-cypher-examples

In particular, the [Neo4jWorkflowExample](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jWorkflowExample.scala) uses a file-based Propertygraph data source that reads from CSV files. [Here](https://github.com/opencypher/cypher-for-apache-spark/tree/master/spark-cypher-examples/src/main/resources/csv/products) is an example of a graph represented in CSV files.

**Comment by s1ck** [comment]
As an alternative you can use Spark's CSV capabilities to read any CSV file and convert it to node and relationship tables on your own. Those tables can then be used as input for CAPS as demonstrated in another [example](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/DataFrameInputExample.scala).

**Comment by HADDADENICAR** [comment]
In your example *InputDataFrame* you have created a dataframe for **nodes** and another for **relationships**,and then you have converted them to tables.

however all my data exists in one dataframe, and i m planning to create from the dataframe nodes and relationships , is that possible ?

**Comment by Mats-SX** [comment]
It is possible, but there isn't any convenient APIs for that just yet. There's a class `SingleTableGraph` you could inspect to see if you can wrap your `DataFrame` with the necessary metadata to consider it a graph in CAPS.

The recommended way right now would be to split your single `DataFrame` into several, one for each label or relationship type.

**Comment by HADDADENICAR** [comment]
Ok , I have Splat the dataframe and created this tables:

        val Pickup_Table = CAPSNodeTable(Set("Pickups"), pickup_dataframe)
        val Dropoff_Table = CAPSNodeTable(Set("Dropoff"), dropoff_dataframe)
        val Trip_Table = CAPSRelationshipTable("Trip", trip_data_dataframe) 

what i want is to connect the **Pickups** with the **Dropoffs** with the relationship **Trip**.

in *InputDataFrameExample* you use only one table for nodes and another for relationship to create the graph : 

     val personTable = CAPSNodeTable(Set("Person"), nodesDF)
     val friendsTable = CAPSRelationshipTable("KNOWS", relsDF)

     // 4) Create property graph from graph scans
     val graph = session.readFrom(personTable, friendsTable)

**Comment by s1ck** [comment]
If you look at the [signature](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher/src/main/scala/org/opencypher/spark/api/CAPSSession.scala#L97) of the `readFrom` method, you can see that it actually takes 1 to n entity tables. In your case, you can just pass in `session.readFrom(pickupTable, dropoffTable, tripTable)`.

**Comment by Mats-SX** [comment]
In order for `:Pickups` and `:Dropoffs` to be connected with the `:Trip`s, the table (dataframe) for `:Trip` needs to have its start and end ids intersect with the node ids of its endpoints; the relationship table describes which nodes are connected to which based on ids.

For reference, please check out the Cypher style guide on recommended ways to name your labels and relationship types: https://github.com/opencypher/openCypher/blob/master/docs/style-guide.adoc#31-graph-modelling

**Comment by HADDADENICAR** [comment]
@Mats-SX and how would i do that i mean the creation and 
 the connection of ids in the relationship

**Comment by Mats-SX** [comment]
If node with id 0 is to be connected to node with id 1 you need to have a relationship with start id 0 and end id 1.

A very simple layout would be:

Nodes: (just id, no properties)
```
id
0
1
2
```

Relationships: (just the mandatory fields)
```
id | start | end
0 | 0 | 1
1 | 0 | 2
```

This is a graph with three nodes and two relationships.

**Comment by HADDADENICAR** [comment]
with help i get in *slack* i tipped this code : 

    package org.opencypher.spark.examples
    import org.apache.spark.sql.functions.udf
    import org.apache.spark.sql.types._
    import org.apache.spark.sql.{DataFrame, Row, SparkSession}
    import org.opencypher.spark.api.CAPSSession
    import org.opencypher.spark.api.io.{CAPSNodeTable, CAPSRelationshipTable}
    import org.opencypher.spark.util.ConsoleApp
    import java.net.URI
    import org.opencypher.okapi.api.io.conversion.NodeMapping
    import org.opencypher.okapi.api.io.conversion.RelationshipMapping
    import org.opencypher.spark.api.io.neo4j.Neo4jPropertyGraphDataSource
    import org.opencypher.spark.api.io.neo4j.Neo4jConfig
    import org.apache.spark.sql.functions._
    import org.opencypher.okapi.api.graph.GraphName

    object DataFrameInputExample extends ConsoleApp {
     //1) Create CAPS session and retrieve Spark session
           implicit val session: CAPSSession = CAPSSession.local()
        val spark = session.sparkSession
    
     //2) Load a csv into dataframe
          val df=spark.read.csv("C:\\Users\\Ahmed\\Desktop\\green_result\\part-00000-7015a9f2-f2da-48ab-940f-e1c46aa0b2c4-c000.csv")
    
     //3) cache the dataframe
          val df1=df.cache()
   
     //4) subset the dataframe
    // val trip_data_dataframe=df1.select("_c0","_c3","_c4","_c9","_c10","_c11","_c12","_c13","_c14","_c15","_c16","_c17","_c18","_c19","_c20","_c22")
       val pickup_dataframe=df1.select("_c20","_c21")
       val dropoff_dataframe=df1.select("_c22","_c23")
   
    //5) uncache the dataframe
          df1.unpersist()
  
    //6) add id columns to pickup , dropoff and trip dataframes
       val pickup_dataframe2= pickup_dataframe.withColumn("id1",monotonically_increasing_id).select("id1",pickup_dataframe.columns:_*)
       val dropoff_dataframe2= dropoff_dataframe.withColumn("id2",monotonically_increasing_id).select("id2",dropoff_dataframe.columns:_*)
       //  val trip_data_dataframe2= trip_data_dataframe.withColumn("id3",monotonically_increasing_id).select("id","_c0","_c3","_c4","_c9","_c10","_c11","_c12","_c13","_c14","_c15","_c16","_c17","_c18","_c19","_c22","_c20")
       val trip_data_dataframe=pickup_dataframe2.withColumn("idj",monotonically_increasing_id).join(dropoff_dataframe2.withColumn("idj",monotonically_increasing_id),"idj")
      
    //7) reordering the columns of trip dataframe
       trip_data_dataframe.show()
    val trip_data_dataframe2=trip_data_dataframe.select("idj","id1","id2","_c20","_c21","_c22","_c23")
       trip_data_dataframe2.show()
      
    //8) mapping the columns
      val Pickup_mapping=NodeMapping.withSourceIdKey("id1").withImpliedLabel("Pickup").withPropertyKeys("_c21","_c20")
      val Dropoff_mapping=NodeMapping.withSourceIdKey("id2").withImpliedLabel("Dropoff").withPropertyKeys("_c23","_c22")
      val Trip_mapping=RelationshipMapping.withSourceIdKey("idj").withSourceStartNodeKey("id1").withSourceEndNodeKey("id2").withRelType("TRIP").withPropertyKeys("_c21","_c20","_c23","_c22")
     
    //9)  create tables
      val Pickup_Table2 = CAPSNodeTable(Pickup_mapping, pickup_dataframe2)
      val Dropoff_Table = CAPSNodeTable(Dropoff_mapping, dropoff_dataframe2)
      val Trip_Table = CAPSRelationshipTable(Trip_mapping,trip_data_dataframe2)
    
    //10) Create graph
      val graph = session.readFrom(Pickup_Table2,Dropoff_Table, Trip_Table)
      
    //11)  Connect to Neo4j
      val boltWriteURI: URI = new URI("bolt://localhost:7687")
      val neo4jWriteConfig: Neo4jConfig = new Neo4jConfig(boltWriteURI, "neo4j", Some("wakarimashta"), true)
      val neo4jResult: Neo4jPropertyGraphDataSource = new Neo4jPropertyGraphDataSource(neo4jWriteConfig)(session)
      
     
    //12) Store graph in neo4j
       val neo4jResultName: GraphName = new GraphName("neo4jgraphs");
       neo4jResult.store(neo4jResultName, graph);
        }

Every works fine until the last step  **12) Store graph in neo4j** ; i get this error : 

    Exception in thread "main" org.neo4j.driver.v1.exceptions.DatabaseException: Unable to create CONSTRAINT ON ( ___neo4jgraphs:___neo4jgraphs ) ASSERT ___neo4jgraphs.___morpheusID IS UNIQUE:
    Both Node(66) and Node(70) have the label `___neo4jgraphs` and property `___morpheusID` = 12

do you know how to fix it ?

**Comment by s1ck** [comment]
That caps id is being stored at a node in Neo4j (since you can't manually set the node id in Neo4j). For faster writes we create an index on that specific property (*morpheusID*) which fails if the node ids overlap.

**Comment by HADDADENICAR** [comment]
as i solved that problem in #599 , the solution here ,to generate  automatic ids , is using `monotonically_increasing_id`+ `previous_df.count()` as in this example : 

     val pickup_dataframe2= pickup_dataframe.withColumn("id1",monotonically_increasing_id+pickup_dataframe.count()).select("id1",pickup_dataframe.columns:_*)
     val dropoff_dataframe2= dropoff_dataframe.withColumn("id2",monotonically_increasing_id+pickup_dataframe2.count()+pickup_dataframe.count()).select("id2",dropoff_dataframe.columns:_*)

important to note that the dataframe that make the relationship should identified from 0 with `monotonically_increasing_id`

      //7) create the relationship "trip" is dataframe
     val trip_data_dataframe2=pickup_dataframe2.withColumn("idj",monotonically_increasing_id).join(dropoff_dataframe2.withColumn("idj",monotonically_increasing_id),"idj")

this issue is Solved 👍
