### ISSUE TITLE
Unable to create CONSTRAINT ON ( ___neo4jgraphs:___neo4jgraphs ) ASSERT ___neo4jgraphs.___morpheusID IS UNIQUE

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#599]
Continuing the tries to solve #579 , i  tried to figure out if this error:

    Unable to create CONSTRAINT ON ( ___neo4jgraphs98729:___neo4jgraphs98729 ) ASSERT ___neo4jgraphs98729.___morpheusID IS UNIQUE:
    Both Node(18) and Node(70) have the label `___neo4jgraphs98729` and property `___morpheusID` = 0

 is related to the Spark Dataframes that i have created from the CSV or not.

So i created by my own this 3 Spark dataframes,inspired from yours in InputDataFrame Example:

    object myPickupDF {
       def nodes(session: SparkSession): DataFrame = {
          val nodes = List(
           Row(0L,"dr72jjm","adc0ddeb11"),
           Row(1L, "dr5rsgm","adc0ddeb11"),
           Row(2L,"dr5rzek" ,"adc0ddebb1"),
           Row(3L, "dr5rvg1","adc0ddebb1"),
           Row(4L, "dr5rveq","adc0ddebf1"),
           Row(5L,"dr5rvu3" ,"adc0ddebf1"),
           Row(6L,"dr5ry39" ,"adc0ddebf1"),
           Row(7L, "dr5rxth","adc0ddecb1"),
           Row(8L,"dr5rs3d" ,"adc0ddecb1"),
           Row(9L, "dr72jh5","adc0ddecb1"),
           Row(10L,"dr5rth3" ,"adc0ddecb1"),
           Row(11L, "dr5rvey","adc0ddecf1"),
           Row(12L,"dr5ry28" ,"adc0ddecf1"),
           Row(13L, "dr72jkb","adc0ddedb1"),
           Row(14L, "dr72js5","adc0ddedb1")
            ).asJava
    val nodeSchema = StructType(List(
      StructField("id1", LongType, false),
      StructField("Pickup_geohash", StringType, false),
      StructField("Pickup_timehash", StringType, false))
     )
    session.createDataFrame(nodes, nodeSchema)
      }
    }

    object myDropoffDF {
       def nodes(session: SparkSession): DataFrame = {
         val nodes = List(
           Row(0L,"dr5rkky","adc0de000f"),
           Row(1L, "dr5rkvg","adc0ddefd0"),
           Row(2L,"dr5ru2d" ,"adc0ddf1d0"),
           Row(3L, "dr5rst4","adc0ddf0b0"),
           Row(4L, "dr5rx2e","adc0ddfa10"),
           Row(5L,"dr5rwzg" ,"adc0ddf0b0"),
           Row(6L,"dr5rvgv" ,"adc0ddedf1"),
           Row(7L, "dr5rxf7","adc0ddedf1"),
           Row(8L,"dr5rtjw" ,"adc0ddf0d0"),
           Row(9L, "dr5rkjt","adc0ddfc0f"),
           Row(10L,"dr5rt4w" ,"adc0ddedf1"),
           Row(11L, "dr5ruku","adc0ddf1b0"),
           Row(12L,"dr5ryus" ,"adc0ddeef0"),
           Row(13L, "dr72jt1","adc0ddeed1"),
           Row(14L, "dr5ru32","adc0ddfb10")
           ).asJava
       val nodeSchema = StructType(List(
           StructField("id2", LongType, false),
           StructField("Dropoff_geohash", StringType, false),
           StructField("Dropoff_timehash", StringType, false))
         )
         session.createDataFrame(nodes, nodeSchema)
         }
        }
     object myTripDF {
        def nodes(session: SparkSession): DataFrame = {
        val nodes = List(
           Row(0L,0L,0L),
           Row(1L, 1L,1L),
           Row(2L,2L ,2L),
           Row(3L, 3L,3L),
           Row(4L, 4L,4L),
           Row(5L,5L ,5L),
           Row(6L,6L ,6L),
           Row(7L, 7L,7L),
           Row(8L,8L ,8L),
           Row(9L, 9L,9L),
           Row(10L,10L ,10L),
           Row(11L, 11L,11L),
           Row(12L,12L ,12L),
           Row(13L, 13L,13L),
           Row(14L, 14L,14L)
           ).asJava
        val nodeSchema = StructType(List(
            StructField("idj", LongType, false),
            StructField("Pickup_id", LongType, false),
            StructField("Dropoff_id", LongType, false))
          )
          session.createDataFrame(nodes, nodeSchema)
         }
      }

     val myPickupDF2 = myPickupDF.nodes(spark)
     val myDropoffDF2=myDropoffDF.nodes(spark)
     val myTripDF2=myTripDF.nodes(spark)

Then i add the  **mappings** and **create the tables**:

     //8) mapping the columns
      val Pickup_mapping=NodeMapping.withSourceIdKey("id1").withImpliedLabel("Pickup").withPropertyKeys("Pickup_geohash","Pickup_timehash")
      val Dropoff_mapping=NodeMapping.withSourceIdKey("id2").withImpliedLabel("Dropoff").withPropertyKeys("Dropoff_geohash","Dropoff_timehash")
      val Trip_mapping=RelationshipMapping.withSourceIdKey("idj").withSourceStartNodeKey("Pickup_id").withSourceEndNodeKey("Dropoff_id").withRelType("TRIP")

     //9)  create tables
     val Pickup_Table2 = CAPSNodeTable(Pickup_mapping, myPickupDF2)
     val Dropoff_Table = CAPSNodeTable(Dropoff_mapping, myDropoffDF2)
     val Trip_Table = CAPSRelationshipTable(Trip_mapping,myTripDF2)

And finally i **create the graph** and **store it Neo4j**:

      //10) Create graph
      val graph = session.readFrom(Pickup_Table2,Dropoff_Table, Trip_Table)
      graph.cypher("""MATCH(p:Pickup)-[TRIP]->(d:Dropoff) RETURN p,d""")
      //11)  Connect to Neo4j
     val boltWriteURI: URI = new URI("bolt://localhost:7687")
     val neo4jWriteConfig: Neo4jConfig = new Neo4jConfig(boltWriteURI, "neo4j", Some("wakarimashta"), true)
     val neo4jResult: Neo4jPropertyGraphDataSource = new    Neo4jPropertyGraphDataSource(neo4jWriteConfig)(session)

      //12) Store graph in neo4j
     val neo4jResultName: GraphName = new GraphName("neo4jgraph");
     neo4jResult.store(neo4jResultName, graph);

**Result**: The Same Error occuers again.
In [StackOverFlow](https://stackoverflow.com/questions/51737163/unable-to-create-constraint-on-neo4jgraphs-neo4jgraphs) an expert commented that the problem come from two nodes having the same "**morphisID**" as it s written in the error.
so what 's **morphisID** and how can i make it unique ?

**Comment by s1ck** [comment]
see my reply in #579

**Comment by HADDADENICAR** [comment]
I 've figured out what is the problem:
this error is fired because the dataframes have the same id numbers : 

    df1||df2||df3
     0L||0L ||0L
     1L||1L ||1L
     2L||2L ||2L

to be  fixed each dataframe need to have it's id differents from the other : 

    df1||df2||df3
    0L||3L  ||6L
    1L||4L  ||7L
    2L||5L  ||8L
