### ISSUE TITLE
MERGE the Creation of Nodes with CAPS

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#603]
In #579 i have been able to create a basic graph of pickups and dropoffs, what i noticed is the same node can be repeated  with this solution (it uses CREATE or maybe the problem is in the **id** that make it unique). so i m asking how to merge the creation of the graph:

**if the same node exists, it shouldn't be recreated**

**Comment by HADDADENICAR** [comment]
As i can do by `load` CSV i want t do this with CAPS: 

    load csv from "file:///green_data.csv" as line MERGE(p:HashNode {geohash: line[20]}) ON CREATE set p.pickup=True ,p.timehash=line[21] ON MATCH set p.pickup=True, p.timehash=line[21] MERGE(d:HashNode {geohash: line[22]}) ON CREATE set d.dropoff=True,d.timehash=line[23] ON MATCH set d.dropoff=True,d.timehash=line[23] MERGE (p)-[:trip{VendorID:line[0],RateCodeID:line[4],Passenger_count:line[9],Trip_distance:line[10],Fare_amount:line[11],
    Extra:line[12],MTA_tax:line[13],Tip_amount:line[14],Tolls_amount:line[15],
    Total_amount:line[17],Payment_type:line[18]}]->(d)

**Comment by HADDADENICAR** [comment]
I found a solution to merge the nodes: based on your graph to merge the : 
**pickup nodes**  i run : 

    MATCH (x:HashNode)
    WITH DISTINCT x._c20 AS PickupValue
    MATCH (x:HashNode) WHERE x._c20 = PickupValue
    WITH PickupValue, collect(x) AS nds
    CALL apoc.refactor.mergeNodes(nds) YIELD node
    RETURN node
 **drop off nodes** i run : 

    MATCH (x:HashNode)
    WITH DISTINCT x._c22 AS dropoffValue
    MATCH (x:HashNode) WHERE x._c22 = dropoffValue
    WITH dropoffValue, collect(x) AS nds
    CALL apoc.refactor.mergeNodes(nds) YIELD node
    RETURN node
and to make the **graph connected** (pickup node can be a drop off for another node) i run : 

    MATCH (x:HashNode), (y:HashNode)
    WHERE x._c20=y._c22
    CALL apoc.refactor.mergeNodes([x,y]) YIELD node
    RETURN node

However what i steal need is to run the above code in CAPS , i tried that with ` val graph2=graph.cypher(my query)` but i get an error in the `store()` function mentioning that it is graph result variable.

So how to change the graph using CAPS as it is possible with ***Neo4j Browser*** ??

**Comment by HADDADENICAR** [comment]
beside ***mapping*** isn't there another way to create graphs from a Spark dataframe with CAPS ?
didn't you think about  creating **oriented** and **connected** graphs from huge datasets bu loading CSV ?

**Comment by pstutz** [comment]
About the first question: We have a PR for doing merges to Neo4j here: https://github.com/opencypher/cypher-for-apache-spark/pull/619
This is an example how to use it: https://github.com/opencypher/cypher-for-apache-spark/blob/9bce42b857e96f3cae1f1f95105c2dbfce8b147e/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jMergeExample.scala

**Comment by pstutz** [comment]
In general the graphs in CAPS are immutable and you need to use the `CONSTRUCT` syntax @Mats-SX described to create a new merged graph.

**Comment by pstutz** [comment]
About alternative ways of loading graphs: There's a CSV-based `EdgeList` data source here: https://github.com/opencypher/cypher-for-apache-spark/blob/1d8f5efe537cf6fd966f3b49b8316cca9dd1a23a/spark-cypher/src/main/scala/org/opencypher/spark/api/io/edgelist/EdgeListDataSource.scala

Maybe you can use it as a template for writing your own data source. Is there a standard CSV graph format that you think we should support?

**Comment by pstutz** [comment]
Closing the issue, please feel free to open a new issue for each individual question.

**Comment by HADDADENICAR** [comment]
@Mats-SX  I want to create nodes with `CATALOG` as the following:

    for every distinct geohash : 
      copy the timehash from the intial graph
      create(_new_node{geohash, list_of_timehash})

i tried the following code but it doesn't work : 

    session.cypher ("""
        |  CATALOG CREATE GRAPH nodes {
        | FROM GRAPH session.inputGraph
        | MATCH (n)
        | WITH DISTINCT n.geohash AS geohash
        | FROM GRAPH session.inputGraph
        | match(m) where m.geohash=geohash
        | with collect(m) as nodes
        | unwind nodes as node
        | CONSTRUCT
        | CREATE (h:HashNode{p:node})
        | RETURN GRAPH
           }""".stripMargin)

**Comment by Mats-SX** [comment]
@HADDADENICAR You're comparing a property value to a node. Nodes can not be properties. For reference, see openCypher's [Property Graph Model](https://github.com/opencypher/openCypher/blob/master/docs/property-graph-model.adoc#14-property) on properties.

**Comment by HADDADENICAR** [comment]
geohash is a node  here  ?
what i know is to access a property we use `node.property` and as mean alias isn't ?

**Comment by Mats-SX** [comment]
Apologies, I was being unclear. I was referring to this bit:

```
CREATE (h:HashNode{p:node})
```

This means 
> create a node with the label `:HashNode` and the property `p` with the value `node`

For this to be well-defined the `node` variable must contain only valid property values. In your query above `node` contains nodes that were matched by `MATCH (m)` and then collected and unwinded, and nodes are not valid property values.

As a side note, `collect()` and `UNWIND` are essentially inverses of one another. Doing them in succession as in your query above is essentially wasted work. See the [Cypher 9 specification](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) for reference of these constructs.

**Comment by HADDADENICAR** [comment]
ok then @Mats-SX  Since `apoc`  isn't implemented in CAPS  could you suggest to me then how to do that  with pURE CYPHER:

    for every distinct geohash : 
      copy the timehash properties from the intial graph
      create(_new_node{geohash, list_of_timehash})

**Comment by Mats-SX** [comment]
Perhaps something like this?

```
WITH geoHash AS geoHash  // assuming an input table of hashes
WITH collect(DISTINCT geoHash) AS distinctHashes
UNWIND distinctHashes AS uniqueHash
FROM timeHashGraph
MATCH (th:TimeHash)
CONSTRUCT
  CREATE (:NewNode {geo: uniqueHash, list: th.listOfTimeHash})
```
