### ISSUE TITLE
[question] Analyze paths in multigraph environment

### ISSUE THREAD

**Issue by conker84** [opencypher/cypher-for-apache-spark#624]
Hi guys,
I'm working on use case that leverage the multigraph feature, I have some CSV files and after some ETL stuff with Spark and CAPS I obtain a graph for each file, which looks like this more or less:

file 1 - Graph 1:

(k__Bacteria)-[:INTERACTION]->(p__Proteobacteria)-[:INTERACTION]->(c__Alphaproteobacteria)-[:INTERACTION]->(o__Rhizobiales)-[:INTERACTION]->(f__Bradyrhizobiaceae)-[:INTERACTION]->(g__Bosea)-[:INTERACTION]->(s__Afipia_genosp_9)

(k__Bacteria)-[:INTERACTION]->(p__Firmicutes)-[:INTERACTION]->(c__Bacilli)-[:INTERACTION]->(o__Bacillales)-[:INTERACTION]->(f__Staphylococcaceae)-[:INTERACTION]->(g__Jeotgalicoccus)-[:INTERACTION]->(Unclassified)

(k__Bacteria)-[:INTERACTION]->(p__Actinobacteria)-[:INTERACTION]->(c__Actinobacteria)-[:INTERACTION]->(o__Actinomycetales)-[:INTERACTION]->(f__Microbacteriaceae)-[:INTERACTION]->(g__Agromyces)-[:INTERACTION]->(Unclassified)

(k__Bacteria)-[:INTERACTION]->(p__Proteobacteria)-[:INTERACTION]->(c__Gammaproteobacteria)-[:INTERACTION]->(o__Xanthomonadales)-[:INTERACTION]->(f__Xanthomonadaceae)-[:INTERACTION]->(g__Xylella)-[:INTERACTION]->(s__Xylella_fastidiosa)

(k__Bacteria)-[:INTERACTION]->(c__Actinobacteria)-[:INTERACTION]->(o__Actinomycetales)-[:INTERACTION]->(Unclassified)

Following an image that help to understand:
![barcode01](https://user-images.githubusercontent.com/1833335/44617372-553aa180-a861-11e8-90a5-88670e5951e5.PNG)

file 2 - Graph 2:

(k__Bacteria)-[:INTERACTION]->(p__Firmicutes)-[:INTERACTION]->(c__Bacilli)-[:INTERACTION]->(o__Bacillales)-[:INTERACTION]->(f__Listeriaceae)-[:INTERACTION]->(g__Listeria)-[:INTERACTION]->(s__Listeria_grayi)

(k__Bacteria)-[:INTERACTION]->(p__Proteobacteria)-[:INTERACTION]->(c__Alphaproteobacteria)-[:INTERACTION]->(o__Rhizobiales)-[:INTERACTION]->(f__Brucellaceae)-[:INTERACTION]->(g__Pseudochrobactrum)-[:INTERACTION]->(Unclassified)

(k__Bacteria)-[:INTERACTION]->(p__Planctomycetes)-[:INTERACTION]->(c__Kueneniae)-[:INTERACTION]->(o__Kueneniales)-[:INTERACTION]->(f__Scalinduaceae)-[:INTERACTION]->(g__Candidatus_Scalindua)-[:INTERACTION]->(Unclassified)

(k__Bacteria)-[:INTERACTION]->(p__Firmicutes)-[:INTERACTION]->(c__Bacilli)-[:INTERACTION]->(o__Bacillales)-[:INTERACTION]->(f__Staphylococcaceae)-[:INTERACTION]->(g__Jeotgalicoccus)-[:INTERACTION]->(Unclassified)

Following an image that help to understand:
![barcode02](https://user-images.githubusercontent.com/1833335/44617374-6a173500-a861-11e8-8ede-ecb533325a80.PNG)

Then Result Graph, in composed by the paths (compared by the node.name property) that occours in each graph, so in this (simple) case, the result graph is:

(k__Bacteria)-[:INTERACTION]->(p__Firmicutes)-[:INTERACTION]->(c__Bacilli)-[:INTERACTION]->(o__Bacillales)-[:INTERACTION]->(f__Staphylococcaceae)-[:INTERACTION]->(g__Jeotgalicoccus)-[:INTERACTION]->(Unclassified)

(k__Bacteria)-[:INTERACTION]->(c__Actinobacteria)-[:INTERACTION]->(o__Actinomycetales)-[:INTERACTION]->(Unclassified)

Which is essentially composed by the two "strings" highlighted in red and green in the images

Is there some query over CAPS that can compare the "strings"?

Thanks a lot!

**Comment by Mats-SX** [comment]
Hi @conker84 and thanks for reaching out to us.

Unfortunately, CAPS does not yet support path patterns. We intend to add this, but it isn't planned in the short-term.

This query should work, but it will not be exactly the same:
```
session.cypher("""
    |FROM GRAPH barcode01
    |MATCH (s:Bacteria {isRoot: "true"})-[rs:INTERACTION*..7]->(t:Bacteria {isLeaf: "true"})
    |RETURN s, rs, t // will return start node, list of relationships, and end node
""".stripMargin).records
```

**Comment by conker84** [comment]
@Mats-SX thanks but I need the path because then I need to compare each node in the path, _I need something like this_:

```
session.cypher("""
    |FROM GRAPH barcode01
    |MATCH p = (s:Bacteria {isRoot: "true"})-[:INTERACTION*..7]->(t:Bacteria {isLeaf: "true"})
    |
    |FROM GRAPH barcode02
    |MATCH p1 = (s1:Bacteria {isRoot: "true"})-[r1:INTERACTION*..7]->(t2:Bacteria {isLeaf: "true"})
    |
    |WHERE nodes(p) = nodes(p1) // This is an oversimplification :), it's just to explain what I need
    |RETURN p
""".stripMargin).records.size
```

Do you think I could leverage some workaround?
Thanks
Andrea

**Comment by Mats-SX** [comment]
@conker84 I understand. You want to find isomorphic subgraphs given input graphs and a pattern.

Given the equality model of Cypher, the query you posted wouldn't work anyway; nodes in different graphs are unequal by definition. The multiple graph extensions does define an _equivalence_ concept that compares nodes on content (labels and properties) instead of identity, but unfortunately that is also unavailable in CAPS right now.

I'm not sure exactly how one could do this, but perhaps using chained `OPTIONAL MATCH` could be an option?

```
FROM GRAPH barcode01
MATCH (s:Bacteria {isRoot: "true"})-[r1:INTERACTION]->(b1:Bacteria)
OPTIONAL MATCH (b1)-[r2:INTERACTION]->(b2:Bacteria)
OPTIONAL MATCH (b2)-[r3:INTERACTION]->(b3:Bacteria)
OPTIONAL MATCH (b3)-[r4:INTERACTION]->(b4:Bacteria)
OPTIONAL MATCH (b4)-[r5:INTERACTION]->(b5:Bacteria)
OPTIONAL MATCH (b5)-[r6:INTERACTION]->(b6:Bacteria)
OPTIONAL MATCH (b6)-[r7:INTERACTION]->(t:Bacteria {isLeaf: "true"})
RETURN s, r1, b1, r2, b2, r3, b3, r4, b4, r5, b5, r6, b6, r7, t
```

That'll return the path you're looking for, but in a much less convenient form. It will also have `null` as value for nodes and relationships that extend beyond the maximum size of the path.

**Comment by conker84** [comment]
Hi, I made some progress here:
```
session.cypher("""
    |FROM GRAPH barcode01
    |MATCH (s01:Bacteria{isRoot: true})-[:INTERACTION*..7]->(i01:Bacteria)
    |
    |FROM GRAPH barcode02
    |MATCH (s02:Bacteria{isRoot: true})-[:INTERACTION*..7]->(i02:Bacteria)
    |
    |WITH s01.operational_taxonomic_unit as otu01, s01.name as root01, collect(i01.name) as names01,
    |s02.operational_taxonomic_unit as otu02, s02.name as root02, collect(i02.name) as names02
    |
    |WHERE root01 = root02
    |RETURN root01
""".stripMargin)
```
Now I want to add  this piece to the WHERE condition:

```
AND length(filter(x IN names01 WHERE x NOT IN names02)) = 0
```

But I get this exception:

```
org.opencypher.okapi.ir.impl.typer.exception.TypingException: Type inference errors: Don't know how to type FilterExpression(FilterScope(Variable(x),Some(In(Variable(x),Variable(names02)))),Variable(names01)) [line 11, column 34 (offset: 405)]
```

**Comment by Mats-SX** [comment]
Nice workaround! I'm sorry to tell you that `filter()` has not been implemented. When we take this on, we will likely focus first on the little more modern _list comprehensions_, which would look like this:

```
AND length([x IN names01 WHERE NOT x IN names02]) = 0
```

In the mean time, perhaps you could do this in a post-filtering step on the resulting `DataFrame`?

```
val records = session.cypher("... RETURN root01, names01, names02").records

val df = records.Df

df.filter() // SQL expression, or Spark UDF
```

**Comment by Mats-SX** [comment]
Hello @conker84 

Are you still blocked by missing `filter()` here, or have you worked around this?

**Comment by conker84** [comment]
Hi @Mats-SX I'm ok with this
