### ISSUE TITLE
Invalid input 't': expected 'l/L' 

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#625]
I am trying to create another graph based on my  initial graph.

after running these code : 

       //11) Create graph
         val graph = session.readFrom(Pickup_Table2,Dropoff_Table, Trip_Table)
              session.catalog.store("inputGraph", graph)
       //12) Creating another graph based on inputgraph
              session.cypher("""  catalog CREATE GRAPH temp { FROM GRAPH graph
                 MATCH (x:picknode)
                 WITH DISTINCT x._c20 AS pickup_geohash, x._c21 as pickup_timehash
                 CONSTRUCT
                 CREATE (n:picknode{c20:pickup_geohash,c21:pickup_timehash})
                 RETURN GRAPH
              }
             """.stripMargin)

i get this error : 

         Exception in thread "main" org.opencypher.v9_1.util.SyntaxException: Invalid input 't': expected 'l/L' (line 1, column 5 (offset: 4))

how to fix ? i think it is a problem related to `CATALOG` ,cause when i delete it i got a different errors  !?

**Comment by DarthMax** [comment]
Hej!
Are you using the latest version of CAPS - 0.1.7? We introduced some syntax changes there.
Best, Max

**Comment by HADDADENICAR** [comment]
Ok i downloaded the last version , but now i get a problem the `Neo4jConfig` folder path is changed where can  i find it ?
previously it was : 
import org.opencypher.spark.api.io.neo4j.Neo4jConfig

**Comment by Mats-SX** [comment]
https://github.com/opencypher/cypher-for-apache-spark/blob/master/okapi-neo4j-io/src/main/scala/org/opencypher/okapi/neo4j/io/Neo4jConfig.scala

**Comment by HADDADENICAR** [comment]
You re right it is a version problem.
thanks for help
