### ISSUE TITLE
How to rename the Dataframe columns in CAPS

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#629]
I need to **rename** some of my data-frame columns in CAPS.

i found that it's possible in spark using `alias` method, but in order to use it i need to import `spark.implicit`.

this import dosen't work in your project, what is it's equivalent ?

**Comment by HADDADENICAR** [comment]
i found  another way to rename the columns : 

    new_df=old_df.toDF("_c20","geohash")

**Comment by DarthMax** [comment]
Another possibility would be to alter the mapping when importing the data frames as a graph like:

```scala
val mapping = NodeMapping.on("id2").withPropertyKey("geoHash" -> "_c22").withPropertyKey("a" -> "_c23")
```

**Comment by Mats-SX** [comment]
@HADDADENICAR Could you please provide a code example of the import that doesn't work? Normally any import of a Spark package should work the same way it would on vanilla Spark.

**Comment by HADDADENICAR** [comment]
@Mats-SX  in InputDataFrameExample when i add `import spark.implicits._`  i  get an error telling ***"Cannot resolve symbol spark"***

**Comment by Mats-SX** [comment]
@HADDADENICAR You have to add that line after introducing the `spark` variable. That is, after row 45.

https://stackoverflow.com/questions/10537277/what-does-this-import-exactly-mean-in-scala
