### ISSUE TITLE
Use more fine-granular versioning for schema

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#636]
Version `1.1`: Can be read by anyone that could read version `1.0`
Version `2.0`: Throws incompatible schema error for previous CAPS versions

**Comment by pstutz** [comment]
Connected with https://github.com/opencypher/cypher-for-apache-spark/issues/631

**Comment by Mats-SX** [comment]
What kind of change do you imagine that would result in a compatible version bump? I can see many changes that would result in incompatible :)

**Comment by DarthMax** [comment]
Maybe adding an optional property like the schema patterns would be backwards compatible. When reading a schema without them we could simply assume that every thing is possible (like we do right now already)
