### ISSUE TITLE
Problem in Mapping the relationship fields

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#639]
Trying to map my relationship dataframe : 

     val trip_data_dataframe6=trip_data_dataframe5.select("idj","id1","id2","Ehail_fee", "Extra", "Fare_amount", "MTA_tax", "Passenger_count", "Payment_type", "RateCodeID", "Store_and_fwd_flag", "Tip_amount", "Tolls_amount", "Total_amount", "Trip_distance", "Trip_type", "VendorID", "dropoff_timehash", "pickup_timehash")

in a  Trip_Table : 

    val Trip_mapping=RelationshipMapping.withSourceIdKey("idj").withSourceStartNodeKey("id1").withSourceEndNodeKey("id2").withRelType("TRIP").withPropertyKeys(  "Ehail_fee", "Extra", "Fare_amount", "MTA_tax", "Passenger_count", "Payment_type", "RateCodeID", "Store_and_fwd_flag", "Tip_amount", "Tolls_amount", "Total_amount", "Trip_distance", "Trip_type", "VendorID", "dropoff_timehash", "pickup_timehash")

BUT in the graph i get a **value disorder** ; `column a  have the values of column b ` 
also there is a mapped column, RateCodeID, who disappeared .
so is there a limited number of columns that can be mapped ?
and why i get a disorder in result(the graph relationship 's fields) ?

**Comment by HADDADENICAR** [comment]
when i map this data-frame: 
     
     val trip_data_dataframe5= trip_data_dataframe4.toDF("idj","id1","id2","VendorID","Trip_distance","Fare_amount","Extra","MTA_tax","Tip_amount","Tolls_amount","Ehail_fee","Total_amount","Payment_type","Trip_type","Store_and_fwd_flag","RateCodeID","Passenger_count","pickup_timehash","dropoff_timehash")

      val Trip_mapping=RelationshipMapping.withSourceIdKey("idj").withSourceStartNodeKey("id1").withSourceEndNodeKey("id2").withRelType("TRIP").withPropertyKeys(  "VendorID","Trip_distance","Fare_amount","Extra","MTA_tax","Tip_amount","Tolls_amount","Ehail_fee","Total_amount","Payment_type","Trip_type","Store_and_fwd_flag","RateCodeID","Passenger_count","pickup_timehash","dropoff_timehash")


 i got these error : 

    Exception in thread "main" org.opencypher.okapi.impl.exception.IllegalArgumentException: 
    Explanation:
	Use CAPS[Node|Relationship]Table#fromMapping to create a valid EntityTable

    Expected:
	Columns: idj, id1, id2, Ehail_fee, Extra, Fare_amount, MTA_tax, Passenger_count, Payment_type, RateCodeID, Store_and_fwd_flag, Tip_amount, Tolls_amount, Total_amount, Trip_distance, Trip_type, VendorID, dropoff_timehash, pickup_timehash
      Found:
	Columns: idj, id1, id2, VendorID, Trip_distance, Fare_amount, Extra, MTA_tax, Tip_amount, Tolls_amount, Ehail_fee, Total_amount, Payment_type, Trip_type, Store_and_fwd_flag, RateCodeID, Passenger_count, pickup_timehash, dropoff_timehash
	at org.opencypher.okapi.relational.api.io.EntityTable$class.verify(EntityTable.scala:61)

**Comment by pstutz** [comment]
Hi Haddad, do you have a minimal piece of code that allows us to reproduce the issue, or at least the exact code that causes the error and the error output?
There is no limit to the number of property columns mapped. Are the values assigned to the wrong property or are the properties not sorted the way you expect? AFAIK properties on nodes/rels have no order.

**Comment by HADDADENICAR** [comment]
@pstutz   when  i  try to map my data-frame  with these code : 

    val trip_data_dataframe5= trip_data_dataframe4.toDF("idj","id1","id2","VendorID","Trip_distance","Fare_amount","Extra","MTA_tax","Tip_amount","Tolls_amount","Ehail_fee","Total_amount","Payment_type","Trip_type","Store_and_fwd_flag","RateCodeID","Passenger_count","pickup_timehash","dropoff_timehash")

    val Trip_mapping=RelationshipMapping.withSourceIdKey("idj").withSourceStartNodeKey("id1").withSourceEndNodeKey("id2").withRelType("TRIP").withPropertyKeys(  "VendorID","Trip_distance","Fare_amount","Extra","MTA_tax","Tip_amount","Tolls_amount","Ehail_fee","Total_amount","Payment_type","Trip_type","Store_and_fwd_flag","RateCodeID","Passenger_count","pickup_timehash","dropoff_timehash")

i get the previous error : 
  
    Exception in thread "main" org.opencypher.okapi.impl.exception.IllegalArgumentException: 
    Explanation:
      Use CAPS[Node|Relationship]Table#fromMapping to create a valid EntityTable

    Expected:
    Columns: idj, id1, id2, Ehail_fee, Extra, Fare_amount, MTA_tax, Passenger_count, Payment_type, RateCodeID, Store_and_fwd_flag, Tip_amount, Tolls_amount, Total_amount, Trip_distance, Trip_type, VendorID, dropoff_timehash, pickup_timehash
     Found:
    Columns: idj, id1, id2, VendorID, Trip_distance, Fare_amount, Extra, MTA_tax, Tip_amount, Tolls_amount, Ehail_fee, Total_amount, Payment_type, Trip_type, Store_and_fwd_flag, RateCodeID, Passenger_count, pickup_timehash, dropoff_timehash
    
So to solve that error, which i didn't why it occurs, i tired to reorder the columns of my dataframe ,as expected in the error  :

       val trip_data_dataframe6=trip_data_dataframe5.select("idj","id1","id2","Ehail_fee", "Extra", "Fare_amount", "MTA_tax", "Passenger_count", "Payment_type", "RateCodeID", "Store_and_fwd_flag", "Tip_amount", "Tolls_amount", "Total_amount", "Trip_distance", "Trip_type", "VendorID", "dropoff_timehash", "pickup_timehash")

know i didn't get an error , but simply the values of properties in the result neo4j graph aren't true , for example :

*****VendorID*** values are under the property ***Ehail_fee*****
values of Vendor

**Comment by pstutz** [comment]
Are you using `CAPS[Node|Relationship]Table#fromMapping` as the exception suggests? How do you instantiate the actual table?

**Comment by HADDADENICAR** [comment]
I create the trip_mapping table this way : 

      val Trip_Table = CAPSRelationshipTable(Trip_mapping,trip_data_dataframe5)

**Comment by pstutz** [comment]
You should use `CAPSRelationshipTable.fromMapping`, as the exception suggests.

**Comment by HADDADENICAR** [comment]
Ok ,that remove the error too but the mapping is still incorrect :  **VendorID values are under the property Ehail_fee**

**Comment by pstutz** [comment]
What are the property mappings? Does each property mapping refer to a column with the correct column header in the data frame? How did you verify that the mapping is wrong?

It would really help me if I had an executable piece of code to investigate.

**Comment by HADDADENICAR** [comment]
I have news for this problem , i just tried to change as you suggested the `CustomDataFrameInputExample` and i didn't get a problem in mapping , so the problem is another place i will try to find it out and tell you about it.

**Comment by pstutz** [comment]
Thanks for the testing and feedback.

**Comment by s1ck** [comment]
Closing this for now. @HADDADENICAR feel free to open another issue if you find the right cause.
