### ISSUE TITLE
Feature request: Support `RegexMatch`

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#650]
Trying to effect some `slice` and `dice` operations in the Graph with Regex: 

     session.cypher("""
                                      FROM GRAPH inputGraph
                                     |  MATCH (from)-[via]->(to)
                                     |  FROM GRAPH nodes
                                     |  MATCH (n), (m)
                                     |  WHERE from.geohash =~ 'dr5*'
                                     |  CONSTRUCT
                                     |    CREATE (n)-[COPY OF via]->(m)
                                     |  RETURN GRAPH
                                  """.stripMargin).graph
    
i get this exceptions : 

    Exception in thread "main" org.opencypher.okapi.impl.exception.NotImplementedException: Not yet able to convert expression: RegexMatch(Property(Variable(from),PropertyKeyName(geohash)),Parameter(  AUTOSTRING0,String))

**Comment by s1ck** [comment]
https://github.com/opencypher/cypher-for-apache-spark/pull/663
