### ISSUE TITLE
Pathfinding in CAPS-BFS & DFS ?

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#656]
Hello in Cypher/Neo4j there is path finding algorithms such as [***shortestpath***](https://neo4j.com/docs/developer-manual/current/cypher/clauses/match/#query-shortest-path) that return the shortest path between two vertices.
 so i am asking if you have implemented such path search algorithms in CAPS ?

The algorithmes that  i need in my project are *BFS* and *DFS* .

**Comment by Mats-SX** [comment]
I assume you are referring to the `shortestPath` and `allShortestPath` expressions which are described on page 67 of the [openCypher 9 specification](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf).

No, those have not been implemented in CAPS as of this writing.

**Comment by HADDADENICAR** [comment]
@Mats-SX  would they be present in the first release ?  what are the possible Graph Algorithms  beside **Page Rank** IN caps ?

**Comment by Mats-SX** [comment]
There isn't any plan for when these will be available yet.

There are no graph algorithms in CAPS itself, but as illustrated in the example you can "move over" to GraphX and use its functionality. You can also export to Neo4j and use [Neo4j's graph algorithms](https://neo4j.com/developer/graph-algorithms/).

**Comment by HADDADENICAR** [comment]
@Mats-SX  thanks for informations .
