### ISSUE TITLE
PageRank problem  

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#657]
Trying to modify [GraphXPageRankExample](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/GraphXPageRankExample.scala) with my mergeGraph(Created previously with CAPS and stored in the session) : 

      // 3) Query graph with Cypher
      val nodes = mergeGraph.cypher(
        """|MATCH (n:HashNode)
            |RETURN id(n), n.geohash""".stripMargin)

      val rels = mergeGraph.cypher(
         """|MATCH (:HashNode)-[r:TRIP]->(:HashNode)
             |RETURN startNode(r), endNode(r)
    """.stripMargin)

but i get an error : `Cannot resolve asDataFrame`

      // 4) Create GraphX compatible RDDs from nodes and relationships
      val graphXNodeRDD = nodes.records.asDataFrame.rdd.map(row => row.getLong(0) -> row.getString(1))
      val graphXRelRDD = rels.records.asDataFrame.rdd.map(row => Edge(row.getLong(0), row.getLong(1), ()))

**Comment by s1ck** [comment]
Please try `import org.opencypher.spark.api.CAPSSession._` to get the additional method.
