### ISSUE TITLE
How to Conditionally Create a Graph with Cypher?

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#662]
I am trying to create a geohash graph with level 5 of zoom from an existing one with level 7. i tried this code :

    FROM GRAPH mergedGraph
    MATCH (from)-[via]->(to)
    CASE WHEN substring(from.geohash,0,5)=substring(to.geohash,0,5)
    THEN
    CONSTRUCT
    CREATE (h1:HashNode{geohash:substring(from.geohash,0,5)})-[COPY OF via]->  (h1)
    ELSE
    CONSTRUCT create (:HashNode{geohash:substring(from.geohash,0,5)})-[COPY OF via]->  (:HashNode{geohash:substring(to.geohash,0,5)})
    END
    RETURN GRAPH 
But that dosen't seem true in cypher, i get an exception :

      Caused by: org.opencypher.v9_0.util.SyntaxException: Invalid input 'S': expected 'l/L' (line 4, column 4 (offset: 57))

In english words i want  : 
if the  start node and the end node share the same geohash substring then create one node with a relationship that point back to it:
![2018-09-28](https://user-images.githubusercontent.com/35377776/46201835-6f124d00-c315-11e8-8b9d-100810f3b9f2.png)

else create two nodes :

![2018-09-28 1](https://user-images.githubusercontent.com/35377776/46201820-64f04e80-c315-11e8-91c9-ec3e8aa864d5.png)

**Comment by Mats-SX** [comment]
On the error: `CASE` is an expression, and its arguments must also be expressions. `CONSTRUCT` and `CREATE` are clauses, which is a higher-level concept. They may not be used as arguments to `CASE`.

**Comment by HADDADENICAR** [comment]
@s1ck yes exactly

**Comment by HADDADENICAR** [comment]
Thinking about a solution :
1) create the  graph  where start node and end node share the same sub-geohash G1
2) create the  graph  where start node and end node have different sub-geohash G2
3) create a graph that contains both G3=G1+G2
4) create distant nodes from G3 :
    
       session.cypher ("""
        | CATALOG CREATE GRAPH nodes {
        | FROM GRAPH session.G3
        | MATCH (n)
        | WITH DISTINCT n.geohash AS geohash
        |CONSTRUCT
        |   CREATE (h:HashNode{geohash:geohash})
        |RETURN GRAPH
         }""".stripMargin)

5) copy the relationships from G3 and create G4
 
       val G4 = session.cypher("""
                                        FROM GRAPH G3
                                        |  MATCH (from)-[via]->(to)
                                        |  FROM GRAPH nodes
                                        |  MATCH (n), (m)
                                        |  WHERE from.geohash=n.geohash AND to.geohash = m.geohash
                                         construct
                                        |    CREATE (n)-[COPY OF via]->(m)
                                        |  RETURN GRAPH
                                     """.stripMargin).graph

But i still don't know how to do the step 3 and if it's even possible with CAPS ?

**Comment by HADDADENICAR** [comment]
I solved my problem  with this steps:

1) Create a graph with Level 5 from the existing one : 

       //Creation Geohash Graph with level 5 from the initial graph (level 7)
        val Level5 = session.cypher("""
                                 | FROM GRAPH mergeGraph
                                 | MATCH (from)-[via]->(to)
                                 | CONSTRUCT
                                 |  CREATE (:HashNode{geohash:substring(from.geohash,0,5)})-[COPY OF via]->(:HashNode{geohash:substring(to.geohash,0,5)})
                                 | RETURN GRAPH
                                 """.stripMargin).graph

 2) Copy distant nodes from the previous graph : 
     
        session.cypher ("""
          | CATALOG CREATE GRAPH nodes2 {
          | FROM GRAPH session.Level5
          | MATCH (n)
          | WITH DISTINCT n.geohash AS geohash
          |CONSTRUCT
          | CREATE (h:HashNode{geohash:geohash})
          |RETURN GRAPH
           }""".stripMargin)

finally: 3) Create the distant level5 graph by copying relationships from the first one and affecting them to the distant nodes

       val level5= session.cypher("""
                                      FROM GRAPH Level5
                                     |  MATCH (from)-[via]->(to)
                                     |  FROM GRAPH nodes2
                                     |  MATCH (n), (m)
                                     |  WHERE from.geohash=n.geohash AND to.geohash = m.geohash
                                      construct
                                     |    CREATE (n)-[COPY OF via]->(m)
                                     |  RETURN GRAPH
                                  """.stripMargin).graph
![2018-09-30](https://user-images.githubusercontent.com/35377776/46260303-6754d300-c4e4-11e8-96c3-cc3eaff09ef4.png)
