### ISSUE TITLE
Validate EntityKeys vs graph schema

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#664]
When `EntityKeys` specifies a key for a label, it should produce an error if that key references properties that do not exist for the label. If properties exist but are nullable, that should also be an error.

**Comment by pstutz** [comment]
We're working on addressing this in https://github.com/opencypher/cypher-for-apache-spark/pull/670, where we experimentally integrate entity keys into the schema.

**Comment by Mats-SX** [comment]
@pstutz @tobias-johansson Was this fixed in #683? It seems to me that it was.

**Comment by pstutz** [comment]
Not yet, that change isn't integrated with `Neo4jGraphMerge` yet, which still uses its of `EntityKeys`. There's another issue to track that.

**Comment by Mats-SX** [comment]
Fixed in #688
