### ISSUE TITLE
Subgraph Isomorphism

### ISSUE THREAD

**Issue by hoptical** [opencypher/cypher-for-apache-spark#667]
Hi,
Is there any plan for adding subgraph isomorphism and graph matching features in the CAPS?
Thanks.

**Comment by s1ck** [comment]
Hey Hamed, I'm not sure what exactly you are referring to. In CAPS, you can express search pattern graphs via Cypher. The output are subgraphs of the input graphs that are isomorphic to the pattern graphs. To be precise, the node-mappings between pattern graph and subgraph are isomorphic, relationship-mappings are homomorphic.

Are you maybe referring to graph matching in terms of "Given two property graphs, decide if they are isomorphic."

**Comment by hoptical** [comment]
Hey @s1ck 
Thanks for your answer,

Yes. In more detail, I am looking for matching a graph pattern in the database , but I want the inexact type of matching(error-tolerant) and using graph edit distance(GED) methods and metrics to score the matching procedure.

For example, in the example you said, consider this subgraph:
```
CREATE (n:Person)-[:FRIEND_OF]->(:Person {name:"Emily"})
MERGE (n)-[:FRIEND_OF]->(:Person {name: "Emma"})
MERGE (n)-[:IN_RELATION]->(:Person {name: "Ben"})
```
So a person who we don't know his/her name, is fiend of "Emily" and "Emma" and is in relation with "Ben". 
Now we want to match this subgraph with inexact manner in the database to find who is n! . 
Imagine the database has these subgraphes:

1. A Person named "Alice" who is friend of Emily and Sophia
2. A Person named "Megan" who is friend of Emma and Emily in relation with Ben
3. A Person named "Ava" who is friend of Emma and Emily

So the algorithm should at first, find all of these subgraphs and then match the pattern with them and give the most score to subgraph 2 and the least to subgraph 1. So the most probable person would be "Megan" and the least would be "Alice"

This is what I'm looking for.

**Comment by Mats-SX** [comment]
It seems to me that you are looking for something that isn't currently supported by the Cypher language. There's a Cypher Improvement Request (CIR) that discusses a similar concept here: https://github.com/opencypher/openCypher/issues/186.

**Comment by hoptical** [comment]
@Mats-SX 

Yes That's it!
Is that possible for you to estimate the time that this CIR would be implemented?

**Comment by s1ck** [comment]
There is currently no plan to implement that CIR. Therefore, it is impossible to estimate atm.
