### ISSUE TITLE
Check caching/usage of Schema for Neo4j named graph data source

### ISSUE THREAD

**Issue by DarthMax** [opencypher/cypher-for-apache-spark#677]
In morpheus-examples we run 2 queries on the Neo4jDS. However the output warns 6 times about the schema procedure not being installed. That hints towards that the Schema is read/computed multiple times for the same query (which in either cases would lead to significant performance degradation). We should investigate this further. (migrated from Morpheus)

**Comment by Mats-SX** [comment]
Should only request the schema once from the PGDS.
