### ISSUE TITLE
Replace separate entity keys with the ones defined on the schema in Neo4jGraphMerge

### ISSUE THREAD

**Issue by tobias-johansson** [opencypher/cypher-for-apache-spark#682]
Maybe we could do `PropertyGraph.withSchema(...)`? 
This would also force us to consider would happen if one where to drop a label, for instance?
Perhaps `PropertyGraph.withNodeKeys(...)`/`PropertyGraph.withRelationshipKeys(...)` would offer a more manageable interface?

**Comment by pstutz** [comment]
We decided to go with a pragmatic approach where we don't offer methods to change a graph schema. Instead we allow to pass in additional entity keys into `Neo4jGraphMerge`. These additional keys get added to the graph schema before using the entity keys from the schema to do the merge.
