### ISSUE TITLE
Use CAPS in a Zeppelin notebook Update

### ISSUE THREAD

**Issue by Cyb3rWard0g** [opencypher/cypher-for-apache-spark#694]
Good morning team,

Thank you very much for all your hard work on this project! I cant wait to start playing around again with the latest version of CAPS. One thing that I have noticed since the last time I tried the beta release is that the Zeppeling notebook example https://github.com/opencypher/cypher-for-apache-spark/wiki/Use-CAPS-in-a-Zeppelin-notebook in the wiki is still not up to date. I remember trying the default modules presented in the notebook before and it did not work. I had to figure out what module names were needed for some of the steps. Is this something that will be updated soon?? Thank you in advance

**Comment by Mats-SX** [comment]
Hey @Cyb3rWard0g and thanks for your kind words.

Zeppelin does work with CAPS -- in fact we presented at Spark AI Summit a month ago using Zeppelin. You'll find [the recording of the talk here](https://databricks.com/session/matching-patterns-and-constructing-graphs-with-cypher-for-apache-spark).

We'll make sure to update the instructions so you can also do this.

**Comment by Cyb3rWard0g** [comment]
Thank you very much @Mats-SX . Great presentation 👍 I will follow the examples you mentioned there.

**Comment by DarthMax** [comment]
Hej @Cyb3rWard0g we updated the wiki page now to reflect the latest API changes. Thanks for pointing that out :)

**Comment by Cyb3rWard0g** [comment]
Thank you guys! I will give it a try soon :)
