### ISSUE TITLE
Error SET Clause not supported

### ISSUE THREAD

**Issue by shyamrjoshi** [opencypher/cypher-for-apache-spark#709]
I am trying to write the results of spark processing back to neo4j using CAPS. 
I looked at the example Neo4jMergeExample.scala
 https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jMergeExample.scala
and was able to successfully write the results back to Neo4J. This required us to create a copy of the original Neo4J Graph , do updates on this copy and then use the 
Neo4jGraphMerge.merge() method to update the results back to Neo4J.
This method worked for my use case. I am trying to explore how can we do an update to Neo4j using CAPS without creating a copy of the original graph.
I found one way to do this as mentioned in the example Neo4jWorkflowExample.scala 
https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jWorkflowExample.scala. 

I tried this example and am getting the error stating SET Clause is not supported.

code below gives an error stating that SET clause is not supported.
  
  val rankRecords = capsession.cypher(
    """
      |FROM GRAPH ranks
      |MATCH (r)
      |return id(r) as id, r.rank as rank
    """.stripMargin
  )

  rankRecords.records.collect.foreach(record =>
    capsession.cypher(
    s"""
	  |FROM GRAPH neo4j 	
      |MATCH (f:node {id:${record.get("id").get.toCypherString}})
      | SET f.rank = ${record.get("rank").get.toCypherString}
    """.stripMargin)
  )
 
 I am using spark-cypher 0.2.0 
 libraryDependencies += "org.opencypher" % "spark-cypher" % "0.2.0"
 

Stack trace
Exception in thread "main" org.opencypher.okapi.impl.exception.IllegalStateException: Error during IR construction: IRBuilderError(Clause not yet supported: SetClause(List(SetPropertyItem(Property(Variable(f),PropertyKeyName(rank)),Parameter(  AUTODOUBLE1,Float)))))
	at org.opencypher.okapi.ir.impl.IRBuilder$.getTuple(IRBuilder.scala:61)
	at org.opencypher.okapi.ir.impl.IRBuilder$.extract(IRBuilder.scala:66)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.cypherOnGraph(RelationalCypherSession.scala:158)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.cypher(RelationalCypherSession.scala:120)
	at com.example.graphx.LoadNeo4jGraphx$$anonfun$3.apply(LoadNeo4jGraphx.scala:103)
	at com.example.graphx.LoadNeo4jGraphx$$anonfun$3.apply(LoadNeo4jGraphx.scala:102)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.example.graphx.LoadNeo4jGraphx$.delayedEndpoint$com$example$graphx$LoadNeo4jGraphx$1(LoadNeo4jGraphx.scala:102)
	at com.example.graphx.LoadNeo4jGraphx$delayedInit$body.apply(LoadNeo4jGraphx.scala:16)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.example.graphx.LoadNeo4jGraphx$.main(LoadNeo4jGraphx.scala:16)
	at com.example.graphx.LoadNeo4jGraphx.main(LoadNeo4jGraphx.scala)
18/11/04 19:15:16 INFO SparkContext: Invoking stop() from shutdown hook

**Comment by DarthMax** [comment]
Hej @shyamrjoshi !

In CAPS all graphs are immutable (just like Dataframes), so once loaded you can not change or update a graph as you would in Neo4j, that is why the `SET` clause is not supported. However in CAPS you have the opportunity to create new graphs using the `CONSTRUCT` clause. 
In addition in CAPS it is possible to query from different graphs in a single query, which actually gives you the possibility to combine your two queries into a single one like this:

```scala
  val updatedGraph = capsession.cypher(
    """
      |FROM GRAPH ranks
      |MATCH (r)
      |FROM GRAPH neo4j
      |MATCH (f:node)
      |WHERE f.id = id(r)
      |CONSTRUCT 
      |   CREATE (f {rank: r.rank})
      |RETURN GRAPH
    """.stripMargin
  ).graph
```

The resulting graph only contains the nodes bound to `f` (all nodes with label `node` that have a partner in `r`). Having this graph you can now again use the Neo4j merge feature to merge the updated nodes into your Neo4j database.

**Comment by Mats-SX** [comment]
Note that in order for `Neo4jGraphMerge` to work for you, the `rank` property must uniquely identify nodes in the Neo4j graph (it is a _key_ for the node), specified by an `EntityKeys` object. If you need more properties to get a well-defined key, these need to be added in the `CREATE` clause as well.

**Comment by shyamrjoshi** [comment]
Hi Max and Mat,

Thank you for the quick reply.
I am able to write back to Neo4J successfully using the Neo4jGraphMerge.merge(). 

I am also looking at the Neo4jWorkflowExample.scala example where a SET clause is executed using the neo4j.execute(). 
https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jWorkflowExample.scala

  // Query for product recommendations
  val recommendations = recommendationGraph.cypher(
    """|MATCH (person:Person)-[:FRIEND_OF]-(friend:Person),
       |(friend)-[:IS]->(customer:Customer),
       |(customer)-[:BOUGHT]->(product:Product)
       |RETURN person.name AS for, collect(DISTINCT product.title) AS recommendations""".stripMargin)

  // Use Cypher queries to write the product recommendations back to Neo4j
  recommendations.records.collect.foreach { recommendation =>
    neo4j.execute(
      s"""|MATCH (p:Person {name: ${recommendation.get("for").get.toCypherString}})
          |SET p.should_buy = ${recommendation.get("recommendations").get.toCypherString}""".stripMargin)
  }

How can we use the neo4j.execute() to run the SET query on a remote Neo4j instance. (Neo4j running on a machine outside the spark clusters).
neo4j.execute() is part of the Neo4jHarnessUtils.scala, is this something used for testing and not a recommended practice ?

**Comment by Mats-SX** [comment]
@shyamrjoshi The most straight-forward way would be to just instantiate a Neo4j Java Driver instance to your remote server and execute queries from that.

But if you already have a `Neo4jConfig` object created (which you will have in most CAPS apps that use Neo4j somehow) you can also do `import Neo4jHelpers._` and then you'll get an implicit `.cypher` which you can call directly on the `Neo4jConfig` object itself. See for example [SchemaFromProcedure](https://github.com/opencypher/cypher-for-apache-spark/blob/master/okapi-neo4j-io/src/main/scala/org/opencypher/okapi/neo4j/io/SchemaFromProcedure.scala#L46).

I'll make a note to show this in one of the examples.

**Comment by s1ck** [comment]
I updated the example to not use `SET` statements, but the (recommended) `Neo4jGraphMerge` feature: https://github.com/opencypher/cypher-for-apache-spark/pull/710

**Comment by shyamrjoshi** [comment]
Hi Mats,

Thank you for the reply. I am trying to explore CAPS and I also posted a question on [Neo4j Online Community](https://community.neo4j.com/t/what-is-the-recommended-method-to-update-the-results-from-spark-back-to-neo4j/2789/4) . Thanks for your reply on the Neo4j online community. I will continue that thread here (Did not want to open a new issue for the basic question). 
I wanted to get some more insights on how capssession reads from the remote Neo4j Server.
I see that CAPS will only load the nodes/data from remote Neo4j Server (based on the cypher query), when a spark action is performed, like .show() or .store() or any other action on the dataframe is called. However, When a spark action is called, does this load data from remote Neo4j into one spark node (one JVM machine) ? For example, I am querying remote Neo4j server using the below cypher query. This cypher query returns 100,000 vertices.

capsession.cypher("""
|FROM GRAPH neo4j
|Match (n)
|RETURN n
""")

Does all the vertices get store in memory of a single machine (spark master node/cluster manager)? or the capssession reads from the remote Neo4j Server in batches ?

Thanks,
Shyam

**Comment by shyamrjoshi** [comment]
Thanks @s1ck . I will continue to use Neo4jGraphMerge.merge() for my use case. It works smooth. Thanks.
