### ISSUE TITLE
Can you share an architecture document or workflow on how different modules interact in CAPS?

### ISSUE THREAD

**Issue by nagrawal79** [opencypher/cypher-for-apache-spark#728]

**Comment by s1ck** [comment]
Hey, thanks for your interest in the project. Have a look at these [Google Slides](https://docs.google.com/presentation/d/1nuMEbdn-mJCvSsQZLgycLqyC-BsDQd93ZlwPHCbIlTw/edit?usp=sharing) for an up-to-date overview of our modules and how they depend on each other. Please let us know if you have an additional questions.

**Comment by nagrawal79** [comment]
Thanks Martin for sharing the architecture.
