### ISSUE TITLE
How to run the Last version from the Commande Line  ?

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#792]
Hello Team,
the manager of the project that i was working on last summer wants to execute ,now, my work from the commande line (and not from eclipse or Intellij Idea).
In this summer , @pstutz  showed me [here](https://github.com/opencypher/caps-examples/issues/2) this mvn command to run examples:

     mvn scala:run -DmainClass=org.opencypher.example.HelloCypher //(after mvn clean install)

however this last version dosen't contain a *"pom.xml"* , so mvn clean install dosen't work (I see that you use gradle to build)
So how to run from command line ?

**Comment by s1ck** [comment]
I created a PR that allows you to run a specific Gradle job for custom Scala apps: https://github.com/opencypher/cypher-for-apache-spark/pull/793

Let's say you put your main class in `spark-cypher-examples/src/main/scala/` the command would be:
`./gradlew spark-cypher-examples:runApp -PmainClass=org.opencypher.example.HelloCypher`
