### ISSUE TITLE
`licenseFormat` Gradle task uses different license style

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#818]
Our default license style in CAPS:
```
/*
...
 */
```

License added by `licenseFormat` task:
```
/**
...
 */
```

Additional related issue: The license added by `licenseFormat` is not formatted correctly according to our style, so auto-format changes it. Changing the style to our default style would also fix this issue.

**Comment by Mats-SX** [comment]
Double asterisk seems wrong to me. That's a doc comment, not a normal comment.
