### ISSUE TITLE
CSV Graph Creation 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/cypher-for-apache-spark#823]
I noticed that the GraphSources load only property graphs from different data sources for example CSV, so I found that the csv files are formed in a property graph attached with json schema files. is this done manually or there is a way in CAPS project that automatically make the property graph out of CSV node and relationship files?

Thanks in advance for reply

**Comment by pstutz** [comment]
Hi Mohamed, thanks for your interest in CAPS.

The CSV data source can store/load a property graph in this CSV tables + JSON schema format. You could in theory also manually create/arrange the files like this, but I would not generally recommend it.

I would recommend to create a graph with [DataFrames and mappings](https://github.com/opencypher/cypher-for-apache-spark/blob/5c561c313969ec42a6d35b5c9c03e285db3123d8/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/CustomDataFrameInputExample.scala#L56-L94). Please let us know if this doesn't work for your use case or if you have other feedback about the API.

**Comment by MohamedRagabAnas** [comment]
Thank you very much Pstutz for your kind reply, 
what about other HDFS formats such as Parquet, AVRO, ORC ?
Thanks

**Comment by pstutz** [comment]
I'd recommend also loading these other formats with mappings or to alternatively use the SQLPropertyGraphDataSource, which has a DDL language that describes how tables are mapped to a graph. You find the documentation here: https://neo4j.com/docs/morpheus-user-guide/preview/pgds/#pgds-sql

We are always happy to receive feedback.

**Comment by MohamedRagabAnas** [comment]
I wanted to store the graph using these lines of code but this doesn't store the CSV tables +schema JSON . 

  session.registerSource(Namespace("MMM"), GraphSources.fs(rootPath = "file:///home/cloudera/CAPSRRR/CSV").csv)
  session.catalog.store("MMM",graph)

what is missing here or is there any other way for storing them ?

**Comment by pstutz** [comment]
This creates the property graph. In order to store it you need to first create and register a property graph data source with the session catalog. Relevant modified lines to [create/register a PGDS in the session and to store a graph in a PGDS](https://github.com/opencypher/cypher-for-apache-spark/blob/0c4ad45ca6efa2e455f6973c68d4d79a24b46bc9/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/RecommendationExample.scala):
```scala
val csvPgds = GraphSources.fs(rootPath = GraphSources.fs("some/fs/path").csv
caps.registerSource(Namespace("purchases"), csvPgds)
...
caps.catalog.store("purchases.someGraphName", someGraph)
```

**Comment by MohamedRagabAnas** [comment]
Yes, Thank You Philip, this worked with me !!
