### ISSUE TITLE
Id generation

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#88]
Currently, we accept ids of external graphs and hope they never collide with one another. Additionally, the graph projection capabilities need to generate fresh ids for new entities, and they must also not collide with any other ids that may have been imported.

The only way we know of to get guarantees from Spark when it comes to id generation is the function `monotonically_increasing_id()`, which divides the id space per partition to generate unique numbers for each partition, given some assumption on the size of each partition and the number of partitions.

That function could only be reliably used if we also map all incoming graph entity ids to values generated from it -- which is costly. There seems to be no great way of solving this.

**Comment by pstutz** [comment]
Current approach works for graph construction, but this issue remains: https://github.com/opencypher/cypher-for-apache-spark/issues/148

Sharing of IDs across graphs is a more fundamental architectural issue.
