### ISSUE TITLE
Cypher query metrics (running time, CPU, RAMconsumption)

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/cypher-for-apache-spark#901]
Is there any way in CAPS or in cypher that can compute the running time of a cypher query as well as to compute its Memory and CPU load? or should I write scala code for that.

**Comment by Mats-SX** [comment]
If you're looking for the planning phase of CAPS, where it compiles a Spark execution plan for your query, then you can call `PrintTimings.set()` and you'll get some timings printed.

For the actual execution on the Spark cluster, please refer to standard Spark tooling for this.
